/*
 * Copyright (C) 2026 Eugene Hutorny <eugene@hutorny.in.ua>
 *
 * proto23/test/proto-test.cxx - Unit tests for C++23 proto serializer.
 *
 * Uses Boost.UT and the same binary test vectors as the C++26 tests,
 * generated by protoc. Each test round-trips through serialize() then
 * deserialize() and also verifies binary-exact output of serialize().
 *
 * Licensed under MIT License, see full text in LICENSE
 */

#include "data.h"

#include <boost/ut.hpp>

#include <algorithm>
#include <cstddef>
#include <cstring>
#include <iostream>
#include <iterator>
#include <sstream>
#include <span>
#include <spanstream>
#include <string>
#include <string_view>
#include <vector>

namespace testing {

using namespace std::string_view_literals;
using namespace boost::ut;
using namespace boost::ut::bdd;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Build a string (usable as ispanstream) from a string_view of raw bytes
inline auto make_istream(std::string_view sv) {
    return std::ispanstream{sv};
}

/// Serialize msg and return the raw bytes as std::string
template<proto23::message Msg>
std::string to_bytes(const Msg& msg) {
    std::ostringstream oss;
    proto23::serialize(oss, msg);
    return oss.str();
}

/// Round-trip: serialize then deserialize; return the deserialized value
template<proto23::message Msg>
Msg round_trip(const Msg& original) {
    const auto data = to_bytes(original);
    auto in = std::ispanstream{data};
    Msg result{};
    std::ignore = proto23::deserialize(in, result);
    return result;
}

/// Equality helpers for types without operator==

inline bool eq_inner(const Inner& a, const Inner& b) {
    return a.status == b.status && a.v == b.v;
}
inline bool eq_outer(const Outer& a, const Outer& b) {
    return eq_inner(a.inner, b.inner) && a.v == b.v;
}

// Literal operators for proto wire types
[[maybe_unused]] constexpr auto operator""_i32(unsigned long long v) { return int32(v);    }
[[maybe_unused]] constexpr auto operator""_s32(unsigned long long v) { return sint32(v);   }
[[maybe_unused]] constexpr auto operator""_u32(unsigned long long v) { return uint32(v);   }
[[maybe_unused]] constexpr auto operator""_f32(unsigned long long v) { return fixed32(v);  }
[[maybe_unused]] constexpr auto operator""_sf32(unsigned long long v){ return sfixed32(v); }
[[maybe_unused]] constexpr auto operator""_i64(unsigned long long v) { return int64(v);    }
[[maybe_unused]] constexpr auto operator""_s64(unsigned long long v) { return sint64(v);   }
[[maybe_unused]] constexpr auto operator""_u64(unsigned long long v) { return uint64(v);   }
[[maybe_unused]] constexpr auto operator""_f64(unsigned long long v) { return fixed64(v);  }
[[maybe_unused]] constexpr auto operator""_sf64(unsigned long long v){ return sfixed64(v); }

// Negate proto enum types for test convenience
template<typename T>
    requires (proto23::detail::anyof<std::is_same, T,
        sint32, int32, sfixed32, sint64, int64, sfixed64>())
constexpr T operator-(T v) {
    return static_cast<T>(-static_cast<std::underlying_type_t<T>>(v));
}

inline std::string bytes(std::string_view sv) { return std::string{sv}; } //FIXME

// ---------------------------------------------------------------------------
// Deserialization test runner
// ---------------------------------------------------------------------------

/// Run a single deserialise test: feed wire bytes, compare with expected value
template<proto23::message Msg, typename EqFn>
void test_deser(const char* name,
                Msg expected,
                std::string_view wire,
                EqFn eq_fn)
{
    test(name) = [expected = std::move(expected), wire, eq_fn = std::move(eq_fn)] () mutable {
        auto in = make_istream(wire);
        Msg actual{};
        const auto result = proto23::deserialize(in, actual);
        if (wire.empty()) {
            expect(that % !any(result)) << "empty input should yield empty result";
        } else {
            expect(that % any(result)) << "should deserialize at least one field";
        }
        expect(that % eq_fn(actual, expected)) << "value mismatch";
    };
}

/// Simpler variant for types with operator==
template<proto23::message Msg>
void test_deser(const char* name, Msg expected, std::string_view wire) {
    test_deser(name, std::move(expected), wire, [](const Msg& a, const Msg& b) { return a == b; });
}

// ---------------------------------------------------------------------------
// Serialization + round-trip test runner
// ---------------------------------------------------------------------------

template<proto23::message Msg, typename EqFn>
void test_roundtrip(const char* name, const Msg& msg, EqFn&& eq_fn) {
    test(name) = [=] {
        const Msg rt = round_trip(msg);
        expect(that % eq_fn(rt, msg)) << "round-trip value mismatch";
    };
}

template<proto23::message Msg>
void test_roundtrip(const char* name, const Msg& msg) {
    test_roundtrip(name, msg, [](const Msg& a, const Msg& b) { return a == b; });
}

/// Exact binary match: serialize(msg) must equal wire
template<proto23::message Msg>
void test_exact(const char* name, Msg msg, std::string_view wire) {
    test(name) = [msg = std::move(msg), wire] {
        const auto data = to_bytes(msg);
        expect(eq(data.size(), wire.size())) << "wire length mismatch";
        if (data.size() == wire.size()) {
            expect(that % (std::memcmp(data.data(), wire.data(), wire.size()) == 0))
                << "wire bytes mismatch";
        }
    };
}

// ===========================================================================
//  Bool
// ===========================================================================
suite<"des/bool"> bool_deser = [] {
    test_deser("true",  Bool_{true},  "\x08\x01"sv);
    test_deser("false", Bool_{false}, ""sv);
};

suite<"ser/bool"> bool_ser = [] {
    test_exact("true",  Bool_{true},  "\x08\x01"sv);
    test_exact("false", Bool_{false}, ""sv);
};

// ===========================================================================
//  sint32
// ===========================================================================
suite<"des/sint32"> sint32_deser = [] {
    test_deser("neg_max",  SInt_32{-2147483647_s32}, "\x08\xFD\xFF\xFF\xFF\x0F"sv);
    test_deser("-1",       SInt_32{-1_s32},          "\x08\x01"sv);
    test_deser("0",        SInt_32{0_s32},            ""sv);
    test_deser("1",        SInt_32{1_s32},            "\x08\x02"sv);
    test_deser("pos_max",  SInt_32{2147483647_s32},   "\x08\xFE\xFF\xFF\xFF\x0F"sv);
};

suite<"ser/sint32"> sint32_ser = [] {
    test_exact("neg_max",  SInt_32{-2147483647_s32}, "\x08\xFD\xFF\xFF\xFF\x0F"sv);
    test_exact("-1",       SInt_32{-1_s32},          "\x08\x01"sv);
    test_exact("0",        SInt_32{0_s32},            ""sv);
    test_exact("1",        SInt_32{1_s32},            "\x08\x02"sv);
    test_exact("pos_max",  SInt_32{2147483647_s32},   "\x08\xFE\xFF\xFF\xFF\x0F"sv);
};

// ===========================================================================
//  int32 (proto plain varint, two's-complement)
// ===========================================================================
suite<"des/int32"> int32_deser = [] {
    test_deser("neg",  Int_32{-2147483647_i32},
               "\x08\x81\x80\x80\x80\xF8\xFF\xFF\xFF\xFF\x01"sv);
    test_deser("0",    Int_32{0_i32}, ""sv);
    test_deser("pos",  Int_32{2147483647_i32}, "\x08\xFF\xFF\xFF\xFF\x07"sv);
};

suite<"ser/int32"> int32_ser = [] {
    test_exact("neg",  Int_32{-2147483647_i32},
               "\x08\x81\x80\x80\x80\xF8\xFF\xFF\xFF\xFF\x01"sv);
    test_exact("0",    Int_32{0_i32}, ""sv);
    test_exact("pos",  Int_32{2147483647_i32}, "\x08\xFF\xFF\xFF\xFF\x07"sv);
};

// ===========================================================================
//  uint32
// ===========================================================================
suite<"des/uint32"> uint32_deser = [] {
    test_deser("0",   UInt_32{0_u32},          ""sv);
    test_deser("30",  UInt_32{30_u32},          "\x08\x1E"sv);
    test_deser("max", UInt_32{4294967295_u32},  "\x08\xFF\xFF\xFF\xFF\x0F"sv);
};

suite<"ser/uint32"> uint32_ser = [] {
    test_exact("0",   UInt_32{0_u32},          ""sv);
    test_exact("30",  UInt_32{30_u32},          "\x08\x1E"sv);
    test_exact("max", UInt_32{4294967295_u32},  "\x08\xFF\xFF\xFF\xFF\x0F"sv);
};

// ===========================================================================
//  fixed32 / sfixed32
// ===========================================================================
suite<"des/fixed32"> fixed32_deser = [] {
    test_deser("16",  Fixed_32{16_f32},  "\x0D\x10\x00\x00\x00"sv);
    test_deser("0",   Fixed_32{0_f32},   ""sv);
};

suite<"ser/fixed32"> fixed32_ser = [] {
    test_exact("16",  Fixed_32{16_f32},  "\x0D\x10\x00\x00\x00"sv);
    test_exact("0",   Fixed_32{0_f32},   ""sv);
};

suite<"des/sfixed32"> sfixed32_deser = [] {
    test_deser("16",   SFixed_32{16_sf32},  "\x0D\x10\x00\x00\x00"sv);
    test_deser("-16",  SFixed_32{-16_sf32}, "\x0D\xF0\xFF\xFF\xFF"sv);
    test_deser("0",    SFixed_32{0_sf32},   ""sv);
};

suite<"ser/sfixed32"> sfixed32_ser = [] {
    test_exact("16",   SFixed_32{16_sf32},  "\x0D\x10\x00\x00\x00"sv);
    test_exact("-16",  SFixed_32{-16_sf32}, "\x0D\xF0\xFF\xFF\xFF"sv);
    test_exact("0",    SFixed_32{0_sf32},   ""sv);
};

// ===========================================================================
//  int64 / sint64 / uint64 / fixed64 / sfixed64
// ===========================================================================
suite<"des/sint64"> sint64_deser = [] {
    test_deser("-1",    SInt_64{-1_s64},             "\x08\x01"sv);
    test_deser("0",     SInt_64{0_s64},              ""sv);
    test_deser("max64", SInt_64{9223372036854775807_s64},
               "\x08\xFE\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\x01"sv);
};
suite<"ser/sint64"> sint64_ser = [] {
    test_exact("-1",    SInt_64{-1_s64},             "\x08\x01"sv);
    test_exact("0",     SInt_64{0_s64},              ""sv);
};

suite<"des/fixed64"> fixed64_deser = [] {
    test_deser("91", Fixed_64{91_f64},
               "\x09\x5B\x00\x00\x00\x00\x00\x00\x00"sv);
    test_deser("0",  Fixed_64{0_f64},  ""sv);
};
suite<"ser/fixed64"> fixed64_ser = [] {
    test_exact("91", Fixed_64{91_f64},
               "\x09\x5B\x00\x00\x00\x00\x00\x00\x00"sv);
    test_exact("0",  Fixed_64{0_f64},  ""sv);
};

// ===========================================================================
//  float / double
// ===========================================================================
suite<"des/float"> float_deser = [] {
    test_deser("1.1",  Float_{1.1F}, "\x0D\xCD\xCC\x8C\x3F"sv);
    test_deser("0",    Float_{0.0F}, ""sv);
};
suite<"ser/float"> float_ser = [] {
    test_exact("1.1",  Float_{1.1F}, "\x0D\xCD\xCC\x8C\x3F"sv);
};

suite<"des/double"> double_deser = [] {
    test_deser("2.2",  Double_{2.2},   "\x09\x9A\x99\x99\x99\x99\x99\x01\x40"sv);
    test_deser("0",    Double_{0.0},   ""sv);
};
suite<"ser/double"> double_ser = [] {
    test_exact("2.2",  Double_{2.2},   "\x09\x9A\x99\x99\x99\x99\x99\x01\x40"sv);
};

// ===========================================================================
//  String / Chars / CharArray
// ===========================================================================
suite<"des/string"> string_deser = [] {
    test_deser("simple", String{"simple string"},
               "\x0A\x0D\x73\x69\x6D\x70\x6C\x65\x20\x73\x74\x72\x69\x6E\x67"sv);
    test_deser("empty", String{""}, ""sv);
};
suite<"ser/string"> string_ser = [] {
    test_exact("simple", String{"simple string"},
               "\x0A\x0D\x73\x69\x6D\x70\x6C\x65\x20\x73\x74\x72\x69\x6E\x67"sv);
    test_roundtrip("rt/string", String{"hello world"});
};

suite<"des/chars"> chars_deser = [] {
    Chars c{};
    std::memcpy(c.v, "simple chars", 12U);
    test_deser("simple", c,
               "\x0A\x0C\x73\x69\x6D\x70\x6C\x65\x20\x63\x68\x61\x72\x73"sv);
};

suite<"des/chararray"> chararray_deser = [] {
    CharArray c{};
    std::memcpy(c.v.data(), "simple chars", 12U);
    test_deser("simple", c,
               "\x0A\x0C\x73\x69\x6D\x70\x6C\x65\x20\x63\x68\x61\x72\x73"sv);
};

// ===========================================================================
//  Two-field messages
// ===========================================================================
suite<"des/pairs"> pairs_deser = [] {
    test_deser("bool_sint",   Bool_SInt{true, 10},  "\x10\x01\x18\x14"sv);
    test_deser("sint_string", SInt_String{12, "twelve"},
               "\x20\x18\x2A\x06\x74\x77\x65\x6C\x76\x65"sv);
    test_deser("uint_fixed",  UInt_Fixed{16U, 16_f32},
               "\x30\x10\x45\x10\x00\x00\x00"sv);
};

suite<"ser/pairs"> pairs_ser = [] {
    test_exact("bool_sint",   Bool_SInt{true, 10},  "\x10\x01\x18\x14"sv);
    test_exact("sint_string", SInt_String{12, "twelve"},
               "\x20\x18\x2A\x06\x74\x77\x65\x6C\x76\x65"sv);
    test_roundtrip("rt/bool_sint",   Bool_SInt{true, 10});
    test_roundtrip("rt/sint_string", SInt_String{42, "answer"});
};

// ===========================================================================
//  Packed repeated scalars (vectors / arrays)
// ===========================================================================

// Equality helpers for array types without operator==
auto eq_bool_v = [](const Bool_v& a, const Bool_v& b) {
    return std::equal(std::begin(a.v), std::end(a.v), std::begin(b.v));
};

auto eq_fixed32v = [](const Fixed_32v& a, const Fixed_32v& b) {
    return std::equal(std::begin(a.v), std::end(a.v), std::begin(b.v));
};

auto eq_float_v = [](const Float_v& a, const Float_v& b) {
    return std::equal(std::begin(a.v), std::end(a.v), std::begin(b.v));
};

suite<"des/vectors"> vectors_deser = [] {
    test_deser("bool_v",    Bool_v{{true,true,false,true}},
               "\x0A\x04\x01\x01\x00\x01"sv, eq_bool_v);

    test_deser("sint32v",   SInt_32v{{20,21,22,-23}},
               "\x0A\x04\x28\x2A\x2C\x2D"sv);
    test_deser("uint32v",   UInt_32v{{30_u32,31_u32,32_u32,33_u32}},
               "\x0A\x04\x1E\x1F\x20\x21"sv);

    test_deser("fixed32v",  Fixed_32v{{40_f32,41_f32,42_f32,43_f32}},
               "\x0A\x10\x28\x00\x00\x00\x29\x00\x00\x00"
               "\x2A\x00\x00\x00\x2B\x00\x00\x00"sv, eq_fixed32v);

    test_deser("sfixed32v", SFixed_32v{{{50_sf32,51_sf32,52_sf32,-53_sf32}}},
               "\x0A\x10\x32\x00\x00\x00\x33\x00\x00\x00"
               "\x34\x00\x00\x00\xCB\xFF\xFF\xFF"sv);

    test_deser("double_v",  Double_v{{2.2,9.6E12,-3.97E-100,1E9}},
               "\x0A\x20\x9A\x99\x99\x99\x99\x99\x01\x40"
               "\x00\x00\x00\x2E\x59\x76\xA1\x42"
               "\x30\x3C\xAE\xE6\x6D\xC9\x4B\xAB"
               "\x00\x00\x00\x00\x65\xCD\xCD\x41"sv);

    test_deser("float_v",   Float_v{{1.1F,9.6E-12F,3.97E-14F,-1E6F}},
               "\x0A\x10\xCD\xCC\x8C\x3F\x8E\xE2\x28\x2D"
               "\xFC\xCA\x32\x29\x00\x24\x74\xC9"sv, eq_float_v);
};

suite<"ser/vectors"> vectors_ser = [] {
    test_exact("sint32v",  SInt_32v{{20,21,22,-23}},
               "\x0A\x04\x28\x2A\x2C\x2D"sv);
    test_exact("uint32v",  UInt_32v{{30_u32,31_u32,32_u32,33_u32}},
               "\x0A\x04\x1E\x1F\x20\x21"sv);

    test_roundtrip("rt/sint32v",  SInt_32v{{10, 20, -30}});
    test_roundtrip("rt/uint32v",  UInt_32v{{1_u32, 2_u32, 3_u32}});
    test_roundtrip("rt/double_v", Double_v{{1.0, 2.0, 3.0}});
};

// ===========================================================================
//  Nested messages
// ===========================================================================
auto eq_inner_field = [](const Outer& a, const Outer& b) {
    return eq_outer(a, b);
};

suite<"des/messages"> messages_deser = [] {
    test_deser("outer", Outer{{Status::OK, 2}, 1},
               "\x0A\x04\x08\x2A\x10\x04\x10\x02"sv, eq_inner_field);
    test_deser("outer2", Outer{{Status::NOTOK, 65535}, 8388607},
               "\x0A\x04\x10\xFE\xFF\x07\x10\xFE\xFF\xFF\x07"sv, eq_inner_field);
};

suite<"ser/messages"> messages_ser = [] {
    test_exact("outer", Outer{{Status::OK, 2}, 1},
               "\x0A\x04\x08\x2A\x10\x04\x10\x02"sv);
    test_roundtrip("rt/outer", Outer{{Status::OK, 2}, 1}, eq_inner_field);
};

// ===========================================================================
//  Oneof
// ===========================================================================
inline bool eq_union(const Union& a, const Union& b) {
    if (a.v != b.v) { return false; }
    if (a.v == 1)   { return std::abs(a.value - b.value) < 1e-6; }
    return a.count == b.count;
}

suite<"des/oneof"> oneof_deser = [] {
    // Variant (std::variant)
    test_deser("variant_double", Variant{1, {1.0}},
               "\x08\x02\x11\x00\x00\x00\x00\x00\x00\xF0\x3F"sv);
    test_deser("variant_int",    Variant{2, {2}},
               "\x08\x04\x18\x04"sv);

    // Union — needs custom equality
    test_deser("union_double", Union{1, {.value=1.0}},
               "\x08\x02\x11\x00\x00\x00\x00\x00\x00\xF0\x3F"sv, eq_union);
    test_deser("union_int",    Union{2, {.count=2}},
               "\x08\x04\x18\x04"sv, eq_union);
};

suite<"ser/oneof"> oneof_ser = [] {
    test_exact("variant_double", Variant{1, {1.0}},
               "\x08\x02\x11\x00\x00\x00\x00\x00\x00\xF0\x3F"sv);
    test_exact("variant_int",    Variant{2, {2}},
               "\x08\x04\x18\x04"sv);
    test_roundtrip("rt/variant_double", Variant{1, {1.0}});
    test_roundtrip("rt/variant_int",    Variant{3, {42}});
    test_roundtrip("rt/variant_string", Variant{0, {}});
};

// ===========================================================================
//  Optional
// ===========================================================================
auto eq_optional = [](const Optional& a, const Optional& b) {
    if (a.v != b.v) { return false; }
    if (a.inner.has_value() != b.inner.has_value()) { return false; }
    if (!a.inner.has_value()) { return true; }
    return eq_inner(*a.inner, *b.inner);
};

suite<"des/optional"> optional_deser = [] {
    test_deser("both",
               Optional{Inner{Status::OK, 2}, 1},
               "\x0A\x04\x08\x2A\x10\x04\x10\x02"sv, eq_optional);
    test_deser("none",
               Optional{{}, 1},
               "\x10\x02"sv, eq_optional);
};

suite<"ser/optional"> optional_ser = [] {
    test_exact("both",
               Optional{Inner{Status::OK, 2}, 1},
               "\x0A\x04\x08\x2A\x10\x04\x10\x02"sv);
    test_roundtrip("rt/both",  Optional{Inner{Status::OK, 42}, 7}, eq_optional);
    test_roundtrip("rt/none",  Optional{{}, 3},                    eq_optional);
};

// ===========================================================================
//  unique_ptr (Pointer)
// ===========================================================================
auto eq_pointer = [](const Pointer& a, const Pointer& b) {
    if (a.v != b.v) { return false; }
    if ((a.inner == nullptr) != (b.inner == nullptr)) { return false; }
    if (!a.inner) { return true; }
    return eq_inner(*a.inner, *b.inner);
};

suite<"des/pointer"> pointer_deser = [] {
    test_deser("with_inner",
               Pointer{std::make_unique<Inner>(Inner{Status::OK, 2}), 1},
               "\x0A\x04\x08\x2A\x10\x04\x10\x02"sv, eq_pointer);
    test_deser("no_inner",
               Pointer{{}, 1},
               "\x10\x02"sv, eq_pointer);
};

suite<"ser/pointer"> pointer_ser = [] {
    test_exact("with_inner",
               Pointer{std::make_unique<Inner>(Inner{Status::OK, 2}), 1},
               "\x0A\x04\x08\x2A\x10\x04\x10\x02"sv);
    // round-trip
    test("rt/pointer_with_inner") = [] {
        Pointer orig{std::make_unique<Inner>(Inner{Status::OK, 42}), 7};
        const auto rt = round_trip(orig);
        expect(that % eq_pointer(rt, orig));
    };
};

// ===========================================================================
//  Map
// ===========================================================================
auto eq_map = [](const Map& a, const Map& b) {
    return a.v == b.v && a.dict == b.dict;
};

suite<"des/map"> map_deser = [] {
    test_deser("map1",
               Map{1, {{0, "OK"},{1,"Good"}}},
               "\x08\x02\x12\x06\x08\x00\x12\x02\x4F\x4B"
               "\x12\x08\x08\x02\x12\x04\x47\x6F\x6F\x64"sv, eq_map);
};

suite<"ser/map"> map_ser = [] {
    test_roundtrip("rt/map", Map{1, {{0, "OK"},{1,"Good"}}}, eq_map);
};

// ===========================================================================
//  Result operators (unit tests for Result<N>)
// ===========================================================================
suite<"result"> result_tests = [] {
    using R2 = proto23::detail::result_type<2U>;

    test("default is empty") = [] {
        R2 r{};
        expect(that % !r.any());
        expect(that % !r.all());
        expect(r.errors() == parse_error::none);
    };

    test("set one field") = [] {
        R2 r{};
        r.set(1U, parse_error::none);
        expect(that % r.any());
        expect(that % !r.all());
    };

    test("set all fields") = [] {
        R2 r{};
        r.set(0U, parse_error::none);
        r.set(1U, parse_error::none);
        expect(that % r.any());
        expect(that % r.all());
    };

    test("error accumulated") = [] {
        R2 r{};
        r.set(0U, parse_error::integer_overflow);
        r.set(1U, parse_error::array_overrun);
        expect(that % (r.errors() == (parse_error::array_overrun | parse_error::integer_overflow)));
    };
};

auto eq_extmodel = [](const ExtModel& a, const ExtModel& b) {
    return a.a == b.a && a.b == b.b && a.c == b.c && a.d == b.d && a.e == b.e && a.status == b.status;
};

static_assert(proto23::detail::has_external_model<ExtModel>);
static_assert(message<ExtModel>);

suite<"extmodel"> extern_ = [] {
    test_roundtrip("ExtModel", ExtModel{2, 3, sint32{4}, int32{5}, fixed32{6}, Status::OK}, eq_extmodel);
};

// ===========================================================================
//  Concepts (compile-time checks)
// ===========================================================================
static_assert(proto23::message<Bool_>);
static_assert(proto23::message<Inner>);
static_assert(proto23::message<Outer>);
static_assert(proto23::message<Variant>);
static_assert(proto23::message<Combined>);
static_assert(!proto23::message<int>);
static_assert(!proto23::message<std::string>);

static_assert(proto23::detail::variant_integral<bool>);
static_assert(proto23::detail::variant_integral<std::uint32_t>);
static_assert(proto23::detail::variant_integral<proto23::int32>);
static_assert(proto23::detail::variant_integral<Status>);
static_assert(proto23::detail::zigzag_integral<std::int32_t>);
static_assert(proto23::detail::zigzag_integral<proto23::sint32>);
static_assert(proto23::detail::fixed_arithmetic<proto23::fixed32>);
static_assert(proto23::detail::fixed_arithmetic<double>);

} // namespace testing
