// Generated by protoc-gen-proto23 -- DO NOT EDIT
// Source: packed_field_test.proto

#pragma once

#include <proto23/proto23.h>

#include <cstddef>
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>

namespace google::protobuf::python::internal {

struct TestPackedTypes;
struct TestUnpackedTypes;

struct TestPackedTypes {
    enum class NestedEnum : std::int32_t {
        FOO = 0,
        BAR = 1,
        BAZ = 2,
    };

    std::vector<proto23::int32> repeated_int32{};
    std::vector<proto23::int64> repeated_int64{};
    std::vector<std::uint32_t> repeated_uint32{};
    std::vector<std::uint64_t> repeated_uint64{};
    std::vector<std::int32_t> repeated_sint32{};
    std::vector<std::int64_t> repeated_sint64{};
    std::vector<proto23::fixed32> repeated_fixed32{};
    std::vector<proto23::fixed64> repeated_fixed64{};
    std::vector<proto23::sfixed32> repeated_sfixed32{};
    std::vector<proto23::sfixed64> repeated_sfixed64{};
    std::vector<float> repeated_float{};
    std::vector<double> repeated_double{};
    std::vector<bool> repeated_bool{};
    std::vector<TestPackedTypes::NestedEnum> repeated_nested_enum{};

    using Model = proto23::Fields<
        proto23::Field<&TestPackedTypes::repeated_int32, 1>,
        proto23::Field<&TestPackedTypes::repeated_int64, 2>,
        proto23::Field<&TestPackedTypes::repeated_uint32, 3>,
        proto23::Field<&TestPackedTypes::repeated_uint64, 4>,
        proto23::Field<&TestPackedTypes::repeated_sint32, 5>,
        proto23::Field<&TestPackedTypes::repeated_sint64, 6>,
        proto23::Field<&TestPackedTypes::repeated_fixed32, 7>,
        proto23::Field<&TestPackedTypes::repeated_fixed64, 8>,
        proto23::Field<&TestPackedTypes::repeated_sfixed32, 9>,
        proto23::Field<&TestPackedTypes::repeated_sfixed64, 10>,
        proto23::Field<&TestPackedTypes::repeated_float, 11>,
        proto23::Field<&TestPackedTypes::repeated_double, 12>,
        proto23::Field<&TestPackedTypes::repeated_bool, 13>,
        proto23::Field<&TestPackedTypes::repeated_nested_enum, 14>>;
};

struct TestUnpackedTypes {
    std::vector<proto23::int32> repeated_int32{};
    std::vector<proto23::int64> repeated_int64{};
    std::vector<std::uint32_t> repeated_uint32{};
    std::vector<std::uint64_t> repeated_uint64{};
    std::vector<std::int32_t> repeated_sint32{};
    std::vector<std::int64_t> repeated_sint64{};
    std::vector<proto23::fixed32> repeated_fixed32{};
    std::vector<proto23::fixed64> repeated_fixed64{};
    std::vector<proto23::sfixed32> repeated_sfixed32{};
    std::vector<proto23::sfixed64> repeated_sfixed64{};
    std::vector<float> repeated_float{};
    std::vector<double> repeated_double{};
    std::vector<bool> repeated_bool{};
    std::vector<TestPackedTypes::NestedEnum> repeated_nested_enum{};

    using Model = proto23::Fields<
        proto23::Field<&TestUnpackedTypes::repeated_int32, 1, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_int64, 2, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_uint32, 3, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_uint64, 4, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_sint32, 5, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_sint64, 6, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_fixed32, 7, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_fixed64, 8, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_sfixed32, 9, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_sfixed64, 10, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_float, 11, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_double, 12, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_bool, 13, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_nested_enum, 14, proto23::packed_t::no>>;
};

} // namespace google::protobuf::python::internal
