// Generated by protoc-gen-proto23 -- DO NOT EDIT
// Source: proto23_options.proto

#pragma once

#include <proto23/proto23.h>

#include <cstddef>
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>

#include "google/protobuf/descriptor.proto23.h"

namespace test_options {

enum class MessageTypeID : std::int32_t {
    UNSPECIFIED = 0,
    FOO = 1,
    BAR = 2,
};

} // namespace test_options
