// Generated by protoc-gen-proto23 -- DO NOT EDIT
// Source: proto23_inplace_test.proto

#pragma once

#include <proto23/proto23.h>

#include <cstddef>
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>

#include "proto23/options.proto23.h"

struct Outer;
struct and_;
struct InplaceByDefaultTest;
struct ExplicitInplace;
struct NotComplete;

struct Outer {
    std::int32_t int32{};

    using Model = proto23::Fields<
        proto23::Field<&Outer::int32, 1>>;
};

struct and_ {
    std::int32_t int32{};

    using Model = proto23::Fields<
        proto23::Field<&and_::int32, 1>>;
};

struct InplaceByDefaultTest {
    struct Inner {
        std::int32_t int32{};

        using Model = proto23::Fields<
            proto23::Field<&Inner::int32, 1>>;
    };

    std::unique_ptr<Outer> unique_ptr_OuterPDO{};
    InplaceByDefaultTest::Inner inplace_inner{};
    std::unique_ptr<NotComplete> unique_ptr_NotComplete;
    std::optional<InplaceByDefaultTest::Inner> optional_Inner{};
    std::unique_ptr<NotComplete> unique_ptr_NotComplete2;

    using Model = proto23::Fields<
        proto23::Field<&InplaceByDefaultTest::unique_ptr_OuterPDO, 1>,
        proto23::Field<&InplaceByDefaultTest::inplace_inner, 3>,
        proto23::Field<&InplaceByDefaultTest::unique_ptr_NotComplete, 5>,
        proto23::Field<&InplaceByDefaultTest::optional_Inner, 6>,
        proto23::Field<&InplaceByDefaultTest::unique_ptr_NotComplete2, 8>>;
};

struct ExplicitInplace {
    struct Inner {
        std::int32_t int32{};

        using Model = proto23::Fields<
            proto23::Field<&Inner::int32, 1>>;
    };

    Outer inplace_Outer{};
    ExplicitInplace::Inner inplace_Inner{};
    std::unique_ptr<NotComplete> unique_ptr_NotComplete;
    std::optional<ExplicitInplace::Inner> optional_Inner{};
    std::unique_ptr<NotComplete> unique_ptr_NotComplete2;
    std::optional<and_> optional_and_{};
    and_ inplace_and_{};
    proto23::inplace_vector<ExplicitInplace::Inner, 100> inplace_vector_Inner{};
    proto23::inplace_string<200> inplace_string_200{};
    std::vector<NotComplete> std_vector_NotComplete;

    using Model = proto23::Fields<
        proto23::Field<&ExplicitInplace::inplace_Outer, 1>,
        proto23::Field<&ExplicitInplace::inplace_Inner, 3>,
        proto23::Field<&ExplicitInplace::unique_ptr_NotComplete, 5>,
        proto23::Field<&ExplicitInplace::optional_Inner, 6>,
        proto23::Field<&ExplicitInplace::unique_ptr_NotComplete2, 8>,
        proto23::Field<&ExplicitInplace::optional_and_, 9>,
        proto23::Field<&ExplicitInplace::inplace_and_, 10>,
        proto23::Field<&ExplicitInplace::inplace_vector_Inner, 11, proto23::packed_t::no>,
        proto23::Field<&ExplicitInplace::inplace_string_200, 12>,
        proto23::Field<&ExplicitInplace::std_vector_NotComplete, 13, proto23::packed_t::no>>;
};

struct NotComplete {
    std::int32_t int32{};

    using Model = proto23::Fields<
        proto23::Field<&NotComplete::int32, 1>>;
};

