// Generated by protoc-gen-proto23 -- DO NOT EDIT
// Source: proto23_external_types_test.proto

#pragma once

#include <proto23/proto23.h>

#include <cstddef>
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>

#include "proto23/options.proto23.h"
#include "google/protobuf/duration.proto23.h"
#include "google/protobuf/timestamp.proto23.h"
#include "proto23_types_test.proto23.h"

struct ExtrenlTypesTest;

struct ExtrenlTypesTest {
    std::unique_ptr<IntegralTypesTest> unique_ptr_IntegralTypesTest{};
    IntegralTypesTest inplace_IntegralTypesTest{};
    std::unique_ptr<google::protobuf::Duration> unique_ptr_Duration{};
    google::protobuf::Duration inplace_Duration{};
    std::unique_ptr<google::protobuf::Timestamp> unique_ptr_Timestamp{};
    google::protobuf::Timestamp inplace_Timestamp{};

    using Model = proto23::Fields<
        proto23::Field<&ExtrenlTypesTest::unique_ptr_IntegralTypesTest, 1>,
        proto23::Field<&ExtrenlTypesTest::inplace_IntegralTypesTest, 2>,
        proto23::Field<&ExtrenlTypesTest::unique_ptr_Duration, 3>,
        proto23::Field<&ExtrenlTypesTest::inplace_Duration, 4>,
        proto23::Field<&ExtrenlTypesTest::unique_ptr_Timestamp, 5>,
        proto23::Field<&ExtrenlTypesTest::inplace_Timestamp, 6>>;
};

