// Generated by protoc-gen-proto23 -- DO NOT EDIT
// Source: proto23_inplace_file_test.proto

#pragma once

#include <proto23/proto23.h>

#include <cstddef>
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>

#include "proto23/options.proto23.h"
#include "google/protobuf/timestamp.proto23.h"

struct Outer2;
struct InplaceByFileDefaultTest;
struct ExplicitNotInplace;
struct NotComplete2;

struct Outer2 {
    std::int32_t int32{};

    using Model = proto23::Fields<
        proto23::Field<&Outer2::int32, 1>>;
};

struct InplaceByFileDefaultTest {
    struct Inner {
        std::int32_t int32{};

        using Model = proto23::Fields<
            proto23::Field<&Inner::int32, 1>>;
    };

    Outer2 inplace_Outer{};
    google::protobuf::Timestamp inplace_Timestamp{};
    InplaceByFileDefaultTest::Inner inplace_inner{};
    std::unique_ptr<NotComplete2> unique_ptr_NotComplete;
    std::optional<InplaceByFileDefaultTest::Inner> optional_Inner{};
    std::unique_ptr<NotComplete2> unique_ptr_NotComplete2;
    std::optional<Outer2> optional_Outer{};
    proto23::inplace_string<64> inplace_string{};
    proto23::inplace_vector<std::int32_t, 16> inplace_vector{};

    using Model = proto23::Fields<
        proto23::Field<&InplaceByFileDefaultTest::inplace_Outer, 1>,
        proto23::Field<&InplaceByFileDefaultTest::inplace_Timestamp, 2>,
        proto23::Field<&InplaceByFileDefaultTest::inplace_inner, 3>,
        proto23::Field<&InplaceByFileDefaultTest::unique_ptr_NotComplete, 5>,
        proto23::Field<&InplaceByFileDefaultTest::optional_Inner, 6>,
        proto23::Field<&InplaceByFileDefaultTest::unique_ptr_NotComplete2, 8>,
        proto23::Field<&InplaceByFileDefaultTest::optional_Outer, 9>,
        proto23::Field<&InplaceByFileDefaultTest::inplace_string, 10>,
        proto23::Field<&InplaceByFileDefaultTest::inplace_vector, 11>>;
};

struct ExplicitNotInplace {
    struct Inner {
        std::int32_t int32{};

        using Model = proto23::Fields<
            proto23::Field<&Inner::int32, 1>>;
    };

    std::unique_ptr<Outer2> unique_ptr_Outer{};
    std::unique_ptr<google::protobuf::Timestamp> unique_ptr_Timestamp{};
    std::unique_ptr<ExplicitNotInplace::Inner> unique_ptr_Inner{};
    std::unique_ptr<NotComplete2> unique_ptr_NotComplete2;
    std::unique_ptr<ExplicitNotInplace::Inner> unique_ptr_Inner2{};
    std::unique_ptr<NotComplete2> unique_ptr_NotComplete;
    std::vector<ExplicitNotInplace::Inner> vector_Inner{};
    std::string std_string_200{};
    std::vector<NotComplete2> std_vector_NotComplete;

    using Model = proto23::Fields<
        proto23::Field<&ExplicitNotInplace::unique_ptr_Outer, 1>,
        proto23::Field<&ExplicitNotInplace::unique_ptr_Timestamp, 2>,
        proto23::Field<&ExplicitNotInplace::unique_ptr_Inner, 3>,
        proto23::Field<&ExplicitNotInplace::unique_ptr_NotComplete2, 5>,
        proto23::Field<&ExplicitNotInplace::unique_ptr_Inner2, 6>,
        proto23::Field<&ExplicitNotInplace::unique_ptr_NotComplete, 8>,
        proto23::Field<&ExplicitNotInplace::vector_Inner, 11, proto23::packed_t::no>,
        proto23::Field<&ExplicitNotInplace::std_string_200, 12>,
        proto23::Field<&ExplicitNotInplace::std_vector_NotComplete, 13, proto23::packed_t::no>>;
};

struct NotComplete2 {
    std::int32_t int32{};

    using Model = proto23::Fields<
        proto23::Field<&NotComplete2::int32, 1>>;
};

