// Generated by protoc-gen-proto23 -- DO NOT EDIT
// Source: proto23_change_meaning_test_package.proto

#pragma once

#include <proto23/enum_traits.h>
#include <proto23/proto23.h>

#include <cstddef>
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>

namespace P {

struct Msg;
struct ChangeMeaningToField;

enum class Enum : std::int32_t {
    none = 0,
};

struct Msg {
    std::int32_t int32{};

    using Model = proto23::Fields<
        proto23::Field<&Msg::int32, 1>>;
};

struct ChangeMeaningToField {
    std::unique_ptr<Msg> msg1{};
    bool Msg{};
    Enum enum1{};
    bool Enum{};

    using Model = proto23::Fields<
        proto23::Field<&ChangeMeaningToField::msg1, 1>,
        proto23::Field<&ChangeMeaningToField::Msg, 2>,
        proto23::Field<&ChangeMeaningToField::enum1, 3>,
        proto23::Field<&ChangeMeaningToField::Enum, 4>>;
};

} // namespace P

namespace proto23 {

template<>
struct enum_traits<P::Enum> : 
    proto23::detail::make_enum_traits<P::Enum,0,0,1,0U,true>{};

}
