// Generated by protoc-gen-proto23 -- DO NOT EDIT
// Source: proto23_types_test.proto

#pragma once

#include <proto23/proto23.h>

#include <cstddef>
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>

struct IntegralTypesTest;
struct FloatTypesTest;
struct StringTypesTest;

struct IntegralTypesTest {
    std::int32_t std_int32{};
    proto23::int32 proto23_int32{};
    std::uint32_t std_uint32{};
    proto23::fixed32 proto23_fixed32{};
    proto23::sfixed32 proto23_sfixed32{};
    std::int64_t std_int64{};
    proto23::int64 proto23_int64{};
    std::uint64_t std_uint64{};
    proto23::fixed64 proto23_fixed64{};
    bool plain_bool{};

    using Model = proto23::Fields<
        proto23::Field<&IntegralTypesTest::std_int32, 1>,
        proto23::Field<&IntegralTypesTest::proto23_int32, 2>,
        proto23::Field<&IntegralTypesTest::std_uint32, 3>,
        proto23::Field<&IntegralTypesTest::proto23_fixed32, 4>,
        proto23::Field<&IntegralTypesTest::proto23_sfixed32, 5>,
        proto23::Field<&IntegralTypesTest::std_int64, 6>,
        proto23::Field<&IntegralTypesTest::proto23_int64, 7>,
        proto23::Field<&IntegralTypesTest::std_uint64, 8>,
        proto23::Field<&IntegralTypesTest::proto23_fixed64, 9>,
        proto23::Field<&IntegralTypesTest::plain_bool, 10>>;
};

struct FloatTypesTest {
    float f{};
    double d{};

    using Model = proto23::Fields<
        proto23::Field<&FloatTypesTest::f, 1>,
        proto23::Field<&FloatTypesTest::d, 2>>;
};

struct StringTypesTest {
    std::string s{};
    std::vector<std::byte> b{};
    std::vector<std::vector<std::byte>> r{};

    using Model = proto23::Fields<
        proto23::Field<&StringTypesTest::s, 1>,
        proto23::Field<&StringTypesTest::b, 2>,
        proto23::Field<&StringTypesTest::r, 3>>;
};

