// Generated by protoc-gen-proto23 -- DO NOT EDIT
// Source: proto3_optional.proto

#pragma once

#include <proto23/proto23.h>

#include <cstddef>
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>

struct Proto3Optional;

struct Proto3Optional {
    struct SubMessage {
        std::optional<proto23::int32> int32_field{};
        std::optional<float> float_field{};
        std::optional<double> double_field{};
        std::optional<proto23::int64> int64_field{};
        std::optional<std::uint32_t> uint32_field{};
        std::optional<std::uint64_t> uint64_field{};
        std::optional<std::int32_t> sint32_field{};
        std::optional<std::int64_t> sint64_field{};
        std::optional<proto23::fixed32> fixed32_field{};
        std::optional<proto23::fixed64> fixed64_field{};
        std::optional<proto23::sfixed32> sfixed32_field{};
        std::optional<proto23::sfixed64> sfixed64_field{};
        std::optional<bool> bool_field{};
        std::optional<std::string> string_field{};
        std::optional<std::vector<std::byte>> bytes_field{};

        using Model = proto23::Fields<
            proto23::Field<&SubMessage::int32_field, 17>,
            proto23::Field<&SubMessage::float_field, 18>,
            proto23::Field<&SubMessage::double_field, 19>,
            proto23::Field<&SubMessage::int64_field, 20>,
            proto23::Field<&SubMessage::uint32_field, 21>,
            proto23::Field<&SubMessage::uint64_field, 22>,
            proto23::Field<&SubMessage::sint32_field, 23>,
            proto23::Field<&SubMessage::sint64_field, 24>,
            proto23::Field<&SubMessage::fixed32_field, 25>,
            proto23::Field<&SubMessage::fixed64_field, 26>,
            proto23::Field<&SubMessage::sfixed32_field, 27>,
            proto23::Field<&SubMessage::sfixed64_field, 28>,
            proto23::Field<&SubMessage::bool_field, 29>,
            proto23::Field<&SubMessage::string_field, 30>,
            proto23::Field<&SubMessage::bytes_field, 31>>;
    };

    std::optional<proto23::int32> int32_field{};
    std::optional<float> float_field{};
    std::optional<double> double_field{};
    std::optional<proto23::int64> int64_field{};
    std::optional<std::uint32_t> uint32_field{};
    std::optional<std::uint64_t> uint64_field{};
    std::optional<std::int32_t> sint32_field{};
    std::optional<std::int64_t> sint64_field{};
    std::optional<proto23::fixed32> fixed32_field{};
    std::optional<proto23::fixed64> fixed64_field{};
    std::optional<proto23::sfixed32> sfixed32_field{};
    std::optional<proto23::sfixed64> sfixed64_field{};
    std::optional<bool> bool_field{};
    std::optional<std::string> string_field{};
    std::optional<std::vector<std::byte>> bytes_field{};
    std::optional<Proto3Optional::SubMessage> optional_message{};

    using Model = proto23::Fields<
        proto23::Field<&Proto3Optional::int32_field, 17>,
        proto23::Field<&Proto3Optional::float_field, 18>,
        proto23::Field<&Proto3Optional::double_field, 19>,
        proto23::Field<&Proto3Optional::int64_field, 20>,
        proto23::Field<&Proto3Optional::uint32_field, 21>,
        proto23::Field<&Proto3Optional::uint64_field, 22>,
        proto23::Field<&Proto3Optional::sint32_field, 23>,
        proto23::Field<&Proto3Optional::sint64_field, 24>,
        proto23::Field<&Proto3Optional::fixed32_field, 25>,
        proto23::Field<&Proto3Optional::fixed64_field, 26>,
        proto23::Field<&Proto3Optional::sfixed32_field, 27>,
        proto23::Field<&Proto3Optional::sfixed64_field, 28>,
        proto23::Field<&Proto3Optional::bool_field, 29>,
        proto23::Field<&Proto3Optional::string_field, 30>,
        proto23::Field<&Proto3Optional::bytes_field, 31>,
        proto23::Field<&Proto3Optional::optional_message, 2>>;
};

