// Generated by protoc-gen-proto23 -- DO NOT EDIT
// Source: proto23_message_id_test.proto

#pragma once

#include <proto23/proto23.h>

#include <cstddef>
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>

#include "proto23_options.proto23.h"

namespace test {

struct MessageIDTest;

struct MessageIDTest {
    std::uint32_t v{};

    using Model = proto23::Fields<
        proto23::Field<&MessageIDTest::v, 1>>;
    static constexpr auto MESSAGE_ID = static_cast<::test_options::MessageTypeID>(1);
};

} // namespace test
