// Generated by protoc-gen-proto23 -- DO NOT EDIT
// Source: test_reserved_message_lower.proto

#pragma once

#include <proto23/proto23.h>

#include <cstddef>
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>

namespace lower {

struct abstract;
struct and_;
struct array;
struct as;
struct break_;
struct callable;
struct case_;
struct catch_;
struct class_;
struct clone;
struct const_;
struct continue_;
struct declare;
struct default_;
struct die;
struct do_;
struct echo;
struct else_;
struct elseif;
struct empty;
struct enddeclare;
struct endfor;
struct endforeach;
struct endif;
struct endswitch;
struct endwhile;
struct eval;
struct exit;
struct extends;
struct final;
struct finally;
struct fn;
struct for_;
struct foreach;
struct function;
struct global;
struct goto_;
struct if_;
struct implements;
struct include;
struct include_once;
struct instanceof;
struct insteadof;
struct interface;
struct isset;
struct list;
struct match;
struct namespace_;
struct new_;
struct or_;
struct parent;
struct print;
struct private_;
struct protected_;
struct public_;
struct readonly;
struct require;
struct require_once;
struct return_;
struct self;
struct static_;
struct switch_;
struct throw_;
struct trait;
struct try_;
struct unset;
struct use;
struct var;
struct while_;
struct xor_;
struct yield;
struct int_;
struct float_;
struct bool_;
struct string;
struct true_;
struct false_;
struct null;
struct void_;
struct iterable;
struct TestReservedLowerMessageField;
struct TestReservedLowerRepeatedMessageField;
struct TestReservedLowerOptionalMessageField;

struct abstract {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&abstract::b, 1>>;
};

struct and_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&and_::b, 1>>;
};

struct array {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&array::b, 1>>;
};

struct as {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&as::b, 1>>;
};

struct break_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&break_::b, 1>>;
};

struct callable {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&callable::b, 1>>;
};

struct case_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&case_::b, 1>>;
};

struct catch_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&catch_::b, 1>>;
};

struct class_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&class_::b, 1>>;
};

struct clone {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&clone::b, 1>>;
};

struct const_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&const_::b, 1>>;
};

struct continue_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&continue_::b, 1>>;
};

struct declare {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&declare::b, 1>>;
};

struct default_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&default_::b, 1>>;
};

struct die {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&die::b, 1>>;
};

struct do_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&do_::b, 1>>;
};

struct echo {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&echo::b, 1>>;
};

struct else_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&else_::b, 1>>;
};

struct elseif {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&elseif::b, 1>>;
};

struct empty {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&empty::b, 1>>;
};

struct enddeclare {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&enddeclare::b, 1>>;
};

struct endfor {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&endfor::b, 1>>;
};

struct endforeach {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&endforeach::b, 1>>;
};

struct endif {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&endif::b, 1>>;
};

struct endswitch {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&endswitch::b, 1>>;
};

struct endwhile {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&endwhile::b, 1>>;
};

struct eval {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&eval::b, 1>>;
};

struct exit {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&exit::b, 1>>;
};

struct extends {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&extends::b, 1>>;
};

struct final {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&final::b, 1>>;
};

struct finally {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&finally::b, 1>>;
};

struct fn {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&fn::b, 1>>;
};

struct for_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&for_::b, 1>>;
};

struct foreach {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&foreach::b, 1>>;
};

struct function {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&function::b, 1>>;
};

struct global {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&global::b, 1>>;
};

struct goto_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&goto_::b, 1>>;
};

struct if_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&if_::b, 1>>;
};

struct implements {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&implements::b, 1>>;
};

struct include {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&include::b, 1>>;
};

struct include_once {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&include_once::b, 1>>;
};

struct instanceof {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&instanceof::b, 1>>;
};

struct insteadof {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&insteadof::b, 1>>;
};

struct interface {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&interface::b, 1>>;
};

struct isset {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&isset::b, 1>>;
};

struct list {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&list::b, 1>>;
};

struct match {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&match::b, 1>>;
};

struct namespace_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&namespace_::b, 1>>;
};

struct new_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&new_::b, 1>>;
};

struct or_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&or_::b, 1>>;
};

struct parent {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&parent::b, 1>>;
};

struct print {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&print::b, 1>>;
};

struct private_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&private_::b, 1>>;
};

struct protected_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&protected_::b, 1>>;
};

struct public_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&public_::b, 1>>;
};

struct readonly {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&readonly::b, 1>>;
};

struct require {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&require::b, 1>>;
};

struct require_once {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&require_once::b, 1>>;
};

struct return_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&return_::b, 1>>;
};

struct self {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&self::b, 1>>;
};

struct static_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&static_::b, 1>>;
};

struct switch_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&switch_::b, 1>>;
};

struct throw_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&throw_::b, 1>>;
};

struct trait {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&trait::b, 1>>;
};

struct try_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&try_::b, 1>>;
};

struct unset {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&unset::b, 1>>;
};

struct use {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&use::b, 1>>;
};

struct var {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&var::b, 1>>;
};

struct while_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&while_::b, 1>>;
};

struct xor_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&xor_::b, 1>>;
};

struct yield {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&yield::b, 1>>;
};

struct int_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&int_::b, 1>>;
};

struct float_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&float_::b, 1>>;
};

struct bool_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&bool_::b, 1>>;
};

struct string {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&string::b, 1>>;
};

struct true_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&true_::b, 1>>;
};

struct false_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&false_::b, 1>>;
};

struct null {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&null::b, 1>>;
};

struct void_ {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&void_::b, 1>>;
};

struct iterable {
    std::vector<std::byte> b{};

    using Model = proto23::Fields<
        proto23::Field<&iterable::b, 1>>;
};

struct TestReservedLowerMessageField {
    std::unique_ptr<abstract> f1{};
    std::unique_ptr<and_> f2{};
    std::unique_ptr<array> f3{};
    std::unique_ptr<as> f4{};
    std::unique_ptr<break_> f5{};
    std::unique_ptr<callable> f6{};
    std::unique_ptr<case_> f7{};
    std::unique_ptr<catch_> f8{};
    std::unique_ptr<class_> f9{};
    std::unique_ptr<clone> f10{};
    std::unique_ptr<const_> f11{};
    std::unique_ptr<continue_> f12{};
    std::unique_ptr<declare> f13{};
    std::unique_ptr<default_> f14{};
    std::unique_ptr<die> f15{};
    std::unique_ptr<do_> f16{};
    std::unique_ptr<echo> f17{};
    std::unique_ptr<else_> f18{};
    std::unique_ptr<elseif> f19{};
    std::unique_ptr<empty> f20{};
    std::unique_ptr<enddeclare> f21{};
    std::unique_ptr<endfor> f22{};
    std::unique_ptr<endforeach> f23{};
    std::unique_ptr<endif> f24{};
    std::unique_ptr<endswitch> f25{};
    std::unique_ptr<endwhile> f26{};
    std::unique_ptr<eval> f27{};
    std::unique_ptr<exit> f28{};
    std::unique_ptr<extends> f29{};
    std::unique_ptr<final> f30{};
    std::unique_ptr<finally> f31{};
    std::unique_ptr<fn> f32{};
    std::unique_ptr<for_> f33{};
    std::unique_ptr<foreach> f34{};
    std::unique_ptr<function> f35{};
    std::unique_ptr<global> f36{};
    std::unique_ptr<goto_> f37{};
    std::unique_ptr<if_> f38{};
    std::unique_ptr<implements> f39{};
    std::unique_ptr<include> f40{};
    std::unique_ptr<include_once> f41{};
    std::unique_ptr<instanceof> f42{};
    std::unique_ptr<insteadof> f43{};
    std::unique_ptr<interface> f44{};
    std::unique_ptr<isset> f45{};
    std::unique_ptr<list> f46{};
    std::unique_ptr<match> f47{};
    std::unique_ptr<namespace_> f48{};
    std::unique_ptr<new_> f49{};
    std::unique_ptr<or_> f50{};
    std::unique_ptr<parent> f78{};
    std::unique_ptr<print> f51{};
    std::unique_ptr<private_> f52{};
    std::unique_ptr<protected_> f53{};
    std::unique_ptr<public_> f54{};
    std::unique_ptr<readonly> f80{};
    std::unique_ptr<require> f55{};
    std::unique_ptr<require_once> f56{};
    std::unique_ptr<return_> f57{};
    std::unique_ptr<self> f79{};
    std::unique_ptr<static_> f58{};
    std::unique_ptr<switch_> f59{};
    std::unique_ptr<throw_> f60{};
    std::unique_ptr<trait> f61{};
    std::unique_ptr<try_> f62{};
    std::unique_ptr<unset> f63{};
    std::unique_ptr<use> f64{};
    std::unique_ptr<var> f65{};
    std::unique_ptr<while_> f66{};
    std::unique_ptr<xor_> f67{};
    std::unique_ptr<yield> f68{};
    std::unique_ptr<int_> f69{};
    float f70{};
    bool f71{};
    std::string f72{};
    std::unique_ptr<true_> f73{};
    std::unique_ptr<false_> f74{};
    std::unique_ptr<null> f75{};
    std::unique_ptr<void_> f76{};
    std::unique_ptr<iterable> f77{};

    using Model = proto23::Fields<
        proto23::Field<&TestReservedLowerMessageField::f1, 1>,
        proto23::Field<&TestReservedLowerMessageField::f2, 2>,
        proto23::Field<&TestReservedLowerMessageField::f3, 3>,
        proto23::Field<&TestReservedLowerMessageField::f4, 4>,
        proto23::Field<&TestReservedLowerMessageField::f5, 5>,
        proto23::Field<&TestReservedLowerMessageField::f6, 6>,
        proto23::Field<&TestReservedLowerMessageField::f7, 7>,
        proto23::Field<&TestReservedLowerMessageField::f8, 8>,
        proto23::Field<&TestReservedLowerMessageField::f9, 9>,
        proto23::Field<&TestReservedLowerMessageField::f10, 10>,
        proto23::Field<&TestReservedLowerMessageField::f11, 11>,
        proto23::Field<&TestReservedLowerMessageField::f12, 12>,
        proto23::Field<&TestReservedLowerMessageField::f13, 13>,
        proto23::Field<&TestReservedLowerMessageField::f14, 14>,
        proto23::Field<&TestReservedLowerMessageField::f15, 15>,
        proto23::Field<&TestReservedLowerMessageField::f16, 16>,
        proto23::Field<&TestReservedLowerMessageField::f17, 17>,
        proto23::Field<&TestReservedLowerMessageField::f18, 18>,
        proto23::Field<&TestReservedLowerMessageField::f19, 19>,
        proto23::Field<&TestReservedLowerMessageField::f20, 20>,
        proto23::Field<&TestReservedLowerMessageField::f21, 21>,
        proto23::Field<&TestReservedLowerMessageField::f22, 22>,
        proto23::Field<&TestReservedLowerMessageField::f23, 23>,
        proto23::Field<&TestReservedLowerMessageField::f24, 24>,
        proto23::Field<&TestReservedLowerMessageField::f25, 25>,
        proto23::Field<&TestReservedLowerMessageField::f26, 26>,
        proto23::Field<&TestReservedLowerMessageField::f27, 27>,
        proto23::Field<&TestReservedLowerMessageField::f28, 28>,
        proto23::Field<&TestReservedLowerMessageField::f29, 29>,
        proto23::Field<&TestReservedLowerMessageField::f30, 30>,
        proto23::Field<&TestReservedLowerMessageField::f31, 31>,
        proto23::Field<&TestReservedLowerMessageField::f32, 32>,
        proto23::Field<&TestReservedLowerMessageField::f33, 33>,
        proto23::Field<&TestReservedLowerMessageField::f34, 34>,
        proto23::Field<&TestReservedLowerMessageField::f35, 35>,
        proto23::Field<&TestReservedLowerMessageField::f36, 36>,
        proto23::Field<&TestReservedLowerMessageField::f37, 37>,
        proto23::Field<&TestReservedLowerMessageField::f38, 38>,
        proto23::Field<&TestReservedLowerMessageField::f39, 39>,
        proto23::Field<&TestReservedLowerMessageField::f40, 40>,
        proto23::Field<&TestReservedLowerMessageField::f41, 41>,
        proto23::Field<&TestReservedLowerMessageField::f42, 42>,
        proto23::Field<&TestReservedLowerMessageField::f43, 43>,
        proto23::Field<&TestReservedLowerMessageField::f44, 44>,
        proto23::Field<&TestReservedLowerMessageField::f45, 45>,
        proto23::Field<&TestReservedLowerMessageField::f46, 46>,
        proto23::Field<&TestReservedLowerMessageField::f47, 47>,
        proto23::Field<&TestReservedLowerMessageField::f48, 48>,
        proto23::Field<&TestReservedLowerMessageField::f49, 49>,
        proto23::Field<&TestReservedLowerMessageField::f50, 50>,
        proto23::Field<&TestReservedLowerMessageField::f78, 78>,
        proto23::Field<&TestReservedLowerMessageField::f51, 51>,
        proto23::Field<&TestReservedLowerMessageField::f52, 52>,
        proto23::Field<&TestReservedLowerMessageField::f53, 53>,
        proto23::Field<&TestReservedLowerMessageField::f54, 54>,
        proto23::Field<&TestReservedLowerMessageField::f80, 80>,
        proto23::Field<&TestReservedLowerMessageField::f55, 55>,
        proto23::Field<&TestReservedLowerMessageField::f56, 56>,
        proto23::Field<&TestReservedLowerMessageField::f57, 57>,
        proto23::Field<&TestReservedLowerMessageField::f79, 79>,
        proto23::Field<&TestReservedLowerMessageField::f58, 58>,
        proto23::Field<&TestReservedLowerMessageField::f59, 59>,
        proto23::Field<&TestReservedLowerMessageField::f60, 60>,
        proto23::Field<&TestReservedLowerMessageField::f61, 61>,
        proto23::Field<&TestReservedLowerMessageField::f62, 62>,
        proto23::Field<&TestReservedLowerMessageField::f63, 63>,
        proto23::Field<&TestReservedLowerMessageField::f64, 64>,
        proto23::Field<&TestReservedLowerMessageField::f65, 65>,
        proto23::Field<&TestReservedLowerMessageField::f66, 66>,
        proto23::Field<&TestReservedLowerMessageField::f67, 67>,
        proto23::Field<&TestReservedLowerMessageField::f68, 68>,
        proto23::Field<&TestReservedLowerMessageField::f69, 69>,
        proto23::Field<&TestReservedLowerMessageField::f70, 70>,
        proto23::Field<&TestReservedLowerMessageField::f71, 71>,
        proto23::Field<&TestReservedLowerMessageField::f72, 72>,
        proto23::Field<&TestReservedLowerMessageField::f73, 73>,
        proto23::Field<&TestReservedLowerMessageField::f74, 74>,
        proto23::Field<&TestReservedLowerMessageField::f75, 75>,
        proto23::Field<&TestReservedLowerMessageField::f76, 76>,
        proto23::Field<&TestReservedLowerMessageField::f77, 77>>;
};

struct TestReservedLowerRepeatedMessageField {
    std::vector<abstract> f1{};
    std::vector<and_> f2{};
    std::vector<array> f3{};
    std::vector<as> f4{};
    std::vector<break_> f5{};
    std::vector<callable> f6{};
    std::vector<case_> f7{};
    std::vector<catch_> f8{};
    std::vector<class_> f9{};
    std::vector<clone> f10{};
    std::vector<const_> f11{};
    std::vector<continue_> f12{};
    std::vector<declare> f13{};
    std::vector<default_> f14{};
    std::vector<die> f15{};
    std::vector<do_> f16{};
    std::vector<echo> f17{};
    std::vector<else_> f18{};
    std::vector<elseif> f19{};
    std::vector<empty> f20{};
    std::vector<enddeclare> f21{};
    std::vector<endfor> f22{};
    std::vector<endforeach> f23{};
    std::vector<endif> f24{};
    std::vector<endswitch> f25{};
    std::vector<endwhile> f26{};
    std::vector<eval> f27{};
    std::vector<exit> f28{};
    std::vector<extends> f29{};
    std::vector<final> f30{};
    std::vector<finally> f31{};
    std::vector<fn> f32{};
    std::vector<for_> f33{};
    std::vector<foreach> f34{};
    std::vector<function> f35{};
    std::vector<global> f36{};
    std::vector<goto_> f37{};
    std::vector<if_> f38{};
    std::vector<implements> f39{};
    std::vector<include> f40{};
    std::vector<include_once> f41{};
    std::vector<instanceof> f42{};
    std::vector<insteadof> f43{};
    std::vector<interface> f44{};
    std::vector<isset> f45{};
    std::vector<list> f46{};
    std::vector<match> f47{};
    std::vector<namespace_> f48{};
    std::vector<new_> f49{};
    std::vector<or_> f50{};
    std::vector<parent> f78{};
    std::vector<print> f51{};
    std::vector<private_> f52{};
    std::vector<protected_> f53{};
    std::vector<public_> f54{};
    std::vector<readonly> f80{};
    std::vector<require> f55{};
    std::vector<require_once> f56{};
    std::vector<return_> f57{};
    std::vector<self> f79{};
    std::vector<static_> f58{};
    std::vector<switch_> f59{};
    std::vector<throw_> f60{};
    std::vector<trait> f61{};
    std::vector<try_> f62{};
    std::vector<unset> f63{};
    std::vector<use> f64{};
    std::vector<var> f65{};
    std::vector<while_> f66{};
    std::vector<xor_> f67{};
    std::vector<yield> f68{};
    std::vector<int_> f69{};
    std::vector<float> f70{};
    std::vector<bool> f71{};
    std::vector<std::string> f72{};
    std::vector<true_> f73{};
    std::vector<false_> f74{};
    std::vector<null> f75{};
    std::vector<void_> f76{};
    std::vector<iterable> f77{};

    using Model = proto23::Fields<
        proto23::Field<&TestReservedLowerRepeatedMessageField::f1, 1>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f2, 2>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f3, 3>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f4, 4>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f5, 5>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f6, 6>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f7, 7>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f8, 8>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f9, 9>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f10, 10>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f11, 11>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f12, 12>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f13, 13>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f14, 14>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f15, 15>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f16, 16>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f17, 17>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f18, 18>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f19, 19>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f20, 20>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f21, 21>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f22, 22>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f23, 23>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f24, 24>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f25, 25>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f26, 26>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f27, 27>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f28, 28>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f29, 29>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f30, 30>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f31, 31>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f32, 32>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f33, 33>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f34, 34>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f35, 35>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f36, 36>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f37, 37>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f38, 38>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f39, 39>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f40, 40>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f41, 41>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f42, 42>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f43, 43>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f44, 44>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f45, 45>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f46, 46>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f47, 47>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f48, 48>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f49, 49>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f50, 50>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f78, 78>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f51, 51>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f52, 52>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f53, 53>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f54, 54>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f80, 80>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f55, 55>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f56, 56>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f57, 57>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f79, 79>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f58, 58>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f59, 59>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f60, 60>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f61, 61>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f62, 62>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f63, 63>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f64, 64>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f65, 65>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f66, 66>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f67, 67>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f68, 68>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f69, 69>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f70, 70>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f71, 71>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f72, 72>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f73, 73>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f74, 74>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f75, 75>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f76, 76>,
        proto23::Field<&TestReservedLowerRepeatedMessageField::f77, 77>>;
};

struct TestReservedLowerOptionalMessageField {
    std::unique_ptr<abstract> f1{};
    std::unique_ptr<and_> f2{};
    std::unique_ptr<array> f3{};
    std::unique_ptr<as> f4{};
    std::unique_ptr<break_> f5{};
    std::unique_ptr<callable> f6{};
    std::unique_ptr<case_> f7{};
    std::unique_ptr<catch_> f8{};
    std::unique_ptr<class_> f9{};
    std::unique_ptr<clone> f10{};
    std::unique_ptr<const_> f11{};
    std::unique_ptr<continue_> f12{};
    std::unique_ptr<declare> f13{};
    std::unique_ptr<default_> f14{};
    std::unique_ptr<die> f15{};
    std::unique_ptr<do_> f16{};
    std::unique_ptr<echo> f17{};
    std::unique_ptr<else_> f18{};
    std::unique_ptr<elseif> f19{};
    std::unique_ptr<empty> f20{};
    std::unique_ptr<enddeclare> f21{};
    std::unique_ptr<endfor> f22{};
    std::unique_ptr<endforeach> f23{};
    std::unique_ptr<endif> f24{};
    std::unique_ptr<endswitch> f25{};
    std::unique_ptr<endwhile> f26{};
    std::unique_ptr<eval> f27{};
    std::unique_ptr<exit> f28{};
    std::unique_ptr<extends> f29{};
    std::unique_ptr<final> f30{};
    std::unique_ptr<finally> f31{};
    std::unique_ptr<fn> f32{};
    std::unique_ptr<for_> f33{};
    std::unique_ptr<foreach> f34{};
    std::unique_ptr<function> f35{};
    std::unique_ptr<global> f36{};
    std::unique_ptr<goto_> f37{};
    std::unique_ptr<if_> f38{};
    std::unique_ptr<implements> f39{};
    std::unique_ptr<include> f40{};
    std::unique_ptr<include_once> f41{};
    std::unique_ptr<instanceof> f42{};
    std::unique_ptr<insteadof> f43{};
    std::unique_ptr<interface> f44{};
    std::unique_ptr<isset> f45{};
    std::unique_ptr<list> f46{};
    std::unique_ptr<match> f47{};
    std::unique_ptr<namespace_> f48{};
    std::unique_ptr<new_> f49{};
    std::unique_ptr<or_> f50{};
    std::unique_ptr<parent> f78{};
    std::unique_ptr<print> f51{};
    std::unique_ptr<private_> f52{};
    std::unique_ptr<protected_> f53{};
    std::unique_ptr<public_> f54{};
    std::unique_ptr<readonly> f80{};
    std::unique_ptr<require> f55{};
    std::unique_ptr<require_once> f56{};
    std::unique_ptr<return_> f57{};
    std::unique_ptr<self> f79{};
    std::unique_ptr<static_> f58{};
    std::unique_ptr<switch_> f59{};
    std::unique_ptr<throw_> f60{};
    std::unique_ptr<trait> f61{};
    std::unique_ptr<try_> f62{};
    std::unique_ptr<unset> f63{};
    std::unique_ptr<use> f64{};
    std::unique_ptr<var> f65{};
    std::unique_ptr<while_> f66{};
    std::unique_ptr<xor_> f67{};
    std::unique_ptr<yield> f68{};
    std::unique_ptr<int_> f69{};
    std::optional<float> f70{};
    std::optional<bool> f71{};
    std::optional<std::string> f72{};
    std::unique_ptr<true_> f73{};
    std::unique_ptr<false_> f74{};
    std::unique_ptr<null> f75{};
    std::unique_ptr<void_> f76{};
    std::unique_ptr<iterable> f77{};

    using Model = proto23::Fields<
        proto23::Field<&TestReservedLowerOptionalMessageField::f1, 1>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f2, 2>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f3, 3>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f4, 4>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f5, 5>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f6, 6>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f7, 7>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f8, 8>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f9, 9>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f10, 10>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f11, 11>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f12, 12>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f13, 13>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f14, 14>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f15, 15>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f16, 16>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f17, 17>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f18, 18>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f19, 19>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f20, 20>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f21, 21>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f22, 22>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f23, 23>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f24, 24>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f25, 25>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f26, 26>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f27, 27>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f28, 28>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f29, 29>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f30, 30>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f31, 31>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f32, 32>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f33, 33>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f34, 34>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f35, 35>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f36, 36>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f37, 37>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f38, 38>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f39, 39>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f40, 40>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f41, 41>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f42, 42>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f43, 43>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f44, 44>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f45, 45>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f46, 46>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f47, 47>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f48, 48>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f49, 49>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f50, 50>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f78, 78>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f51, 51>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f52, 52>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f53, 53>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f54, 54>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f80, 80>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f55, 55>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f56, 56>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f57, 57>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f79, 79>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f58, 58>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f59, 59>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f60, 60>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f61, 61>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f62, 62>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f63, 63>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f64, 64>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f65, 65>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f66, 66>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f67, 67>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f68, 68>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f69, 69>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f70, 70>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f71, 71>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f72, 72>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f73, 73>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f74, 74>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f75, 75>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f76, 76>,
        proto23::Field<&TestReservedLowerOptionalMessageField::f77, 77>>;
};

} // namespace lower
