// Generated by protoc-gen-proto23 -- DO NOT EDIT
// Source: test_deprecated.proto

#pragma once

#include <proto23/proto23.h>

#include <cstddef>
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>

namespace test {

struct TestDeprecatedMessage;
struct TestDeprecatedField;

[[deprecated]] enum class TestDeprecatedEnum : std::int32_t {
    UNKNOWN = 0,
};

enum class TestDeprecatedEnumValue : std::int32_t {
    UNSPECIFIED = 0,
    [[deprecated]] DEPRECATED_VALUE = 1,
};

[[deprecated]] struct TestDeprecatedMessage {
    bool foo{};

    using Model = proto23::Fields<
        proto23::Field<&TestDeprecatedMessage::foo, 1>>;
};

struct TestDeprecatedField {
    [[deprecated]] bool foo{};

    using Model = proto23::Fields<
        proto23::Field<&TestDeprecatedField::foo, 1>>;
};

} // namespace test
