// Generated by protoc-gen-proto23 -- DO NOT EDIT
// Source: test_reserved_enum_lower.proto

#pragma once

#include <proto23/enum_traits.h>
#include <proto23/proto23.h>

#include <cstddef>
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>

namespace lower_enum {

enum class abstract : std::int32_t {
    ZERO1 = 0,
};

enum class and_ : std::int32_t {
    ZERO2 = 0,
};

enum class array : std::int32_t {
    ZERO3 = 0,
};

enum class as : std::int32_t {
    ZERO4 = 0,
};

enum class break_ : std::int32_t {
    ZERO5 = 0,
};

enum class callable : std::int32_t {
    ZERO6 = 0,
};

enum class case_ : std::int32_t {
    ZERO7 = 0,
};

enum class catch_ : std::int32_t {
    ZERO8 = 0,
};

enum class class_ : std::int32_t {
    ZERO9 = 0,
};

enum class clone : std::int32_t {
    ZERO10 = 0,
};

enum class const_ : std::int32_t {
    ZERO11 = 0,
};

enum class continue_ : std::int32_t {
    ZERO12 = 0,
};

enum class declare : std::int32_t {
    ZERO13 = 0,
};

enum class default_ : std::int32_t {
    ZERO14 = 0,
};

enum class die : std::int32_t {
    ZERO15 = 0,
};

enum class do_ : std::int32_t {
    ZERO16 = 0,
};

enum class echo : std::int32_t {
    ZERO17 = 0,
};

enum class else_ : std::int32_t {
    ZERO18 = 0,
};

enum class elseif : std::int32_t {
    ZERO19 = 0,
};

enum class empty : std::int32_t {
    ZERO20 = 0,
};

enum class enddeclare : std::int32_t {
    ZERO21 = 0,
};

enum class endfor : std::int32_t {
    ZERO22 = 0,
};

enum class endforeach : std::int32_t {
    ZERO23 = 0,
};

enum class endif : std::int32_t {
    ZERO24 = 0,
};

enum class endswitch : std::int32_t {
    ZERO25 = 0,
};

enum class endwhile : std::int32_t {
    ZERO26 = 0,
};

enum class eval : std::int32_t {
    ZERO27 = 0,
};

enum class exit : std::int32_t {
    ZERO28 = 0,
};

enum class extends : std::int32_t {
    ZERO29 = 0,
};

enum class final : std::int32_t {
    ZERO30 = 0,
};

enum class finally : std::int32_t {
    ZERO31 = 0,
};

enum class fn : std::int32_t {
    ZERO32 = 0,
};

enum class for_ : std::int32_t {
    ZERO33 = 0,
};

enum class foreach : std::int32_t {
    ZERO34 = 0,
};

enum class function : std::int32_t {
    ZERO35 = 0,
};

enum class global : std::int32_t {
    ZERO36 = 0,
};

enum class goto_ : std::int32_t {
    ZERO37 = 0,
};

enum class if_ : std::int32_t {
    ZERO38 = 0,
};

enum class implements : std::int32_t {
    ZERO39 = 0,
};

enum class include : std::int32_t {
    ZERO40 = 0,
};

enum class include_once : std::int32_t {
    ZERO41 = 0,
};

enum class instanceof : std::int32_t {
    ZERO42 = 0,
};

enum class insteadof : std::int32_t {
    ZERO43 = 0,
};

enum class interface : std::int32_t {
    ZERO44 = 0,
};

enum class isset : std::int32_t {
    ZERO45 = 0,
};

enum class list : std::int32_t {
    ZERO46 = 0,
};

enum class match : std::int32_t {
    ZERO47 = 0,
};

enum class namespace_ : std::int32_t {
    ZERO48 = 0,
};

enum class new_ : std::int32_t {
    ZERO49 = 0,
};

enum class or_ : std::int32_t {
    ZERO50 = 0,
};

enum class parent : std::int32_t {
    ZERO78 = 0,
};

enum class print : std::int32_t {
    ZERO51 = 0,
};

enum class private_ : std::int32_t {
    ZERO52 = 0,
};

enum class protected_ : std::int32_t {
    ZERO53 = 0,
};

enum class public_ : std::int32_t {
    ZERO54 = 0,
};

enum class readonly : std::int32_t {
    ZERO80 = 0,
};

enum class require : std::int32_t {
    ZERO55 = 0,
};

enum class require_once : std::int32_t {
    ZERO56 = 0,
};

enum class return_ : std::int32_t {
    ZERO57 = 0,
};

enum class self : std::int32_t {
    ZERO79 = 0,
};

enum class static_ : std::int32_t {
    ZERO58 = 0,
};

enum class switch_ : std::int32_t {
    ZERO59 = 0,
};

enum class throw_ : std::int32_t {
    ZERO60 = 0,
};

enum class trait : std::int32_t {
    ZERO61 = 0,
};

enum class try_ : std::int32_t {
    ZERO62 = 0,
};

enum class unset : std::int32_t {
    ZERO63 = 0,
};

enum class use : std::int32_t {
    ZERO64 = 0,
};

enum class var : std::int32_t {
    ZERO65 = 0,
};

enum class while_ : std::int32_t {
    ZERO66 = 0,
};

enum class xor_ : std::int32_t {
    ZERO67 = 0,
};

enum class yield : std::int32_t {
    ZERO68 = 0,
};

enum class int_ : std::int32_t {
    ZERO69 = 0,
};

enum class float_ : std::int32_t {
    ZERO70 = 0,
};

enum class bool_ : std::int32_t {
    ZERO71 = 0,
};

enum class string : std::int32_t {
    ZERO72 = 0,
};

enum class true_ : std::int32_t {
    ZERO73 = 0,
};

enum class false_ : std::int32_t {
    ZERO74 = 0,
};

enum class null : std::int32_t {
    ZERO75 = 0,
};

enum class void_ : std::int32_t {
    ZERO76 = 0,
};

enum class iterable : std::int32_t {
    ZERO77 = 0,
};

} // namespace lower_enum

namespace proto23 {

template<>
struct enum_traits<lower_enum::abstract> : 
    proto23::detail::make_enum_traits<lower_enum::abstract,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::and_> : 
    proto23::detail::make_enum_traits<lower_enum::and_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::array> : 
    proto23::detail::make_enum_traits<lower_enum::array,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::as> : 
    proto23::detail::make_enum_traits<lower_enum::as,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::break_> : 
    proto23::detail::make_enum_traits<lower_enum::break_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::callable> : 
    proto23::detail::make_enum_traits<lower_enum::callable,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::case_> : 
    proto23::detail::make_enum_traits<lower_enum::case_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::catch_> : 
    proto23::detail::make_enum_traits<lower_enum::catch_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::class_> : 
    proto23::detail::make_enum_traits<lower_enum::class_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::clone> : 
    proto23::detail::make_enum_traits<lower_enum::clone,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::const_> : 
    proto23::detail::make_enum_traits<lower_enum::const_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::continue_> : 
    proto23::detail::make_enum_traits<lower_enum::continue_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::declare> : 
    proto23::detail::make_enum_traits<lower_enum::declare,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::default_> : 
    proto23::detail::make_enum_traits<lower_enum::default_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::die> : 
    proto23::detail::make_enum_traits<lower_enum::die,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::do_> : 
    proto23::detail::make_enum_traits<lower_enum::do_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::echo> : 
    proto23::detail::make_enum_traits<lower_enum::echo,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::else_> : 
    proto23::detail::make_enum_traits<lower_enum::else_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::elseif> : 
    proto23::detail::make_enum_traits<lower_enum::elseif,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::empty> : 
    proto23::detail::make_enum_traits<lower_enum::empty,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::enddeclare> : 
    proto23::detail::make_enum_traits<lower_enum::enddeclare,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::endfor> : 
    proto23::detail::make_enum_traits<lower_enum::endfor,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::endforeach> : 
    proto23::detail::make_enum_traits<lower_enum::endforeach,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::endif> : 
    proto23::detail::make_enum_traits<lower_enum::endif,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::endswitch> : 
    proto23::detail::make_enum_traits<lower_enum::endswitch,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::endwhile> : 
    proto23::detail::make_enum_traits<lower_enum::endwhile,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::eval> : 
    proto23::detail::make_enum_traits<lower_enum::eval,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::exit> : 
    proto23::detail::make_enum_traits<lower_enum::exit,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::extends> : 
    proto23::detail::make_enum_traits<lower_enum::extends,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::final> : 
    proto23::detail::make_enum_traits<lower_enum::final,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::finally> : 
    proto23::detail::make_enum_traits<lower_enum::finally,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::fn> : 
    proto23::detail::make_enum_traits<lower_enum::fn,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::for_> : 
    proto23::detail::make_enum_traits<lower_enum::for_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::foreach> : 
    proto23::detail::make_enum_traits<lower_enum::foreach,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::function> : 
    proto23::detail::make_enum_traits<lower_enum::function,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::global> : 
    proto23::detail::make_enum_traits<lower_enum::global,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::goto_> : 
    proto23::detail::make_enum_traits<lower_enum::goto_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::if_> : 
    proto23::detail::make_enum_traits<lower_enum::if_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::implements> : 
    proto23::detail::make_enum_traits<lower_enum::implements,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::include> : 
    proto23::detail::make_enum_traits<lower_enum::include,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::include_once> : 
    proto23::detail::make_enum_traits<lower_enum::include_once,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::instanceof> : 
    proto23::detail::make_enum_traits<lower_enum::instanceof,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::insteadof> : 
    proto23::detail::make_enum_traits<lower_enum::insteadof,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::interface> : 
    proto23::detail::make_enum_traits<lower_enum::interface,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::isset> : 
    proto23::detail::make_enum_traits<lower_enum::isset,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::list> : 
    proto23::detail::make_enum_traits<lower_enum::list,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::match> : 
    proto23::detail::make_enum_traits<lower_enum::match,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::namespace_> : 
    proto23::detail::make_enum_traits<lower_enum::namespace_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::new_> : 
    proto23::detail::make_enum_traits<lower_enum::new_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::or_> : 
    proto23::detail::make_enum_traits<lower_enum::or_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::parent> : 
    proto23::detail::make_enum_traits<lower_enum::parent,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::print> : 
    proto23::detail::make_enum_traits<lower_enum::print,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::private_> : 
    proto23::detail::make_enum_traits<lower_enum::private_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::protected_> : 
    proto23::detail::make_enum_traits<lower_enum::protected_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::public_> : 
    proto23::detail::make_enum_traits<lower_enum::public_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::readonly> : 
    proto23::detail::make_enum_traits<lower_enum::readonly,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::require> : 
    proto23::detail::make_enum_traits<lower_enum::require,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::require_once> : 
    proto23::detail::make_enum_traits<lower_enum::require_once,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::return_> : 
    proto23::detail::make_enum_traits<lower_enum::return_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::self> : 
    proto23::detail::make_enum_traits<lower_enum::self,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::static_> : 
    proto23::detail::make_enum_traits<lower_enum::static_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::switch_> : 
    proto23::detail::make_enum_traits<lower_enum::switch_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::throw_> : 
    proto23::detail::make_enum_traits<lower_enum::throw_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::trait> : 
    proto23::detail::make_enum_traits<lower_enum::trait,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::try_> : 
    proto23::detail::make_enum_traits<lower_enum::try_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::unset> : 
    proto23::detail::make_enum_traits<lower_enum::unset,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::use> : 
    proto23::detail::make_enum_traits<lower_enum::use,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::var> : 
    proto23::detail::make_enum_traits<lower_enum::var,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::while_> : 
    proto23::detail::make_enum_traits<lower_enum::while_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::xor_> : 
    proto23::detail::make_enum_traits<lower_enum::xor_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::yield> : 
    proto23::detail::make_enum_traits<lower_enum::yield,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::int_> : 
    proto23::detail::make_enum_traits<lower_enum::int_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::float_> : 
    proto23::detail::make_enum_traits<lower_enum::float_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::bool_> : 
    proto23::detail::make_enum_traits<lower_enum::bool_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::string> : 
    proto23::detail::make_enum_traits<lower_enum::string,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::true_> : 
    proto23::detail::make_enum_traits<lower_enum::true_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::false_> : 
    proto23::detail::make_enum_traits<lower_enum::false_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::null> : 
    proto23::detail::make_enum_traits<lower_enum::null,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::void_> : 
    proto23::detail::make_enum_traits<lower_enum::void_,0,0,1,0U,true>{};
template<>
struct enum_traits<lower_enum::iterable> : 
    proto23::detail::make_enum_traits<lower_enum::iterable,0,0,1,0U,true>{};

}
