// Generated by protoc-gen-proto23 -- DO NOT EDIT
// Source: test_reserved_message_upper.proto

#pragma once

#include <proto23/proto23.h>

#include <cstddef>
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>

namespace upper {

struct ABSTRACT;
struct AND;
struct ARRAY;
struct AS;
struct BREAK;
struct CALLABLE;
struct CASE;
struct CATCH;
struct CLASS;
struct CLONE;
struct CONST;
struct CONTINUE;
struct DECLARE;
struct DEFAULT;
struct DIE;
struct DO;
struct ECHO;
struct ELSE;
struct ELSEIF;
struct EMPTY;
struct ENDDECLARE;
struct ENDFOR;
struct ENDFOREACH;
struct ENDIF;
struct ENDSWITCH;
struct ENDWHILE;
struct EVAL;
struct EXIT;
struct EXTENDS;
struct FINAL;
struct FINALLY;
struct FN;
struct FOR;
struct FOREACH;
struct FUNCTION;
struct GLOBAL;
struct GOTO;
struct IF;
struct IMPLEMENTS;
struct INCLUDE;
struct INCLUDE_ONCE;
struct INSTANCEOF;
struct INSTEADOF;
struct INTERFACE;
struct ISSET;
struct LIST;
struct MATCH;
struct NAMESPACE;
struct NEW;
struct OR;
struct PARENT;
struct PRINT;
struct PRIVATE;
struct PROTECTED;
struct PUBLIC;
struct READONLY;
struct REQUIRE;
struct REQUIRE_ONCE;
struct RETURN;
struct SELF;
struct STATIC;
struct SWITCH;
struct THROW;
struct TRAIT;
struct TRY;
struct UNSET;
struct USE;
struct VAR;
struct WHILE;
struct XOR;
struct YIELD;
struct INT;
struct FLOAT;
struct BOOL;
struct STRING;
struct TRUE;
struct FALSE;
struct NULL_;
struct VOID;
struct ITERABLE;

struct ABSTRACT {
    // This message has no fields
};

struct AND {
    // This message has no fields
};

struct ARRAY {
    // This message has no fields
};

struct AS {
    // This message has no fields
};

struct BREAK {
    // This message has no fields
};

struct CALLABLE {
    // This message has no fields
};

struct CASE {
    // This message has no fields
};

struct CATCH {
    // This message has no fields
};

struct CLASS {
    // This message has no fields
};

struct CLONE {
    // This message has no fields
};

struct CONST {
    // This message has no fields
};

struct CONTINUE {
    // This message has no fields
};

struct DECLARE {
    // This message has no fields
};

struct DEFAULT {
    // This message has no fields
};

struct DIE {
    // This message has no fields
};

struct DO {
    // This message has no fields
};

struct ECHO {
    // This message has no fields
};

struct ELSE {
    // This message has no fields
};

struct ELSEIF {
    // This message has no fields
};

struct EMPTY {
    // This message has no fields
};

struct ENDDECLARE {
    // This message has no fields
};

struct ENDFOR {
    // This message has no fields
};

struct ENDFOREACH {
    // This message has no fields
};

struct ENDIF {
    // This message has no fields
};

struct ENDSWITCH {
    // This message has no fields
};

struct ENDWHILE {
    // This message has no fields
};

struct EVAL {
    // This message has no fields
};

struct EXIT {
    // This message has no fields
};

struct EXTENDS {
    // This message has no fields
};

struct FINAL {
    // This message has no fields
};

struct FINALLY {
    // This message has no fields
};

struct FN {
    // This message has no fields
};

struct FOR {
    // This message has no fields
};

struct FOREACH {
    // This message has no fields
};

struct FUNCTION {
    // This message has no fields
};

struct GLOBAL {
    // This message has no fields
};

struct GOTO {
    // This message has no fields
};

struct IF {
    // This message has no fields
};

struct IMPLEMENTS {
    // This message has no fields
};

struct INCLUDE {
    // This message has no fields
};

struct INCLUDE_ONCE {
    // This message has no fields
};

struct INSTANCEOF {
    // This message has no fields
};

struct INSTEADOF {
    // This message has no fields
};

struct INTERFACE {
    // This message has no fields
};

struct ISSET {
    // This message has no fields
};

struct LIST {
    // This message has no fields
};

struct MATCH {
    // This message has no fields
};

struct NAMESPACE {
    // This message has no fields
};

struct NEW {
    // This message has no fields
};

struct OR {
    // This message has no fields
};

struct PARENT {
    // This message has no fields
};

struct PRINT {
    // This message has no fields
};

struct PRIVATE {
    // This message has no fields
};

struct PROTECTED {
    // This message has no fields
};

struct PUBLIC {
    // This message has no fields
};

struct READONLY {
    // This message has no fields
};

struct REQUIRE {
    // This message has no fields
};

struct REQUIRE_ONCE {
    // This message has no fields
};

struct RETURN {
    // This message has no fields
};

struct SELF {
    // This message has no fields
};

struct STATIC {
    // This message has no fields
};

struct SWITCH {
    // This message has no fields
};

struct THROW {
    // This message has no fields
};

struct TRAIT {
    // This message has no fields
};

struct TRY {
    // This message has no fields
};

struct UNSET {
    // This message has no fields
};

struct USE {
    // This message has no fields
};

struct VAR {
    // This message has no fields
};

struct WHILE {
    // This message has no fields
};

struct XOR {
    // This message has no fields
};

struct YIELD {
    // This message has no fields
};

struct INT {
    // This message has no fields
};

struct FLOAT {
    // This message has no fields
};

struct BOOL {
    // This message has no fields
};

struct STRING {
    // This message has no fields
};

struct TRUE {
    // This message has no fields
};

struct FALSE {
    // This message has no fields
};

struct NULL_ {
    // This message has no fields
};

struct VOID {
    // This message has no fields
};

struct ITERABLE {
    // This message has no fields
};

} // namespace upper
