// Generated by protoc-gen-proto23 -- DO NOT EDIT
// Source: test_reserved_enum_upper.proto

#pragma once

#include <proto23/proto23.h>

#include <cstddef>
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>

namespace upper_enum {

enum class ABSTRACT : std::int32_t {
    ZERO1 = 0,
};

enum class AND : std::int32_t {
    ZERO2 = 0,
};

enum class ARRAY : std::int32_t {
    ZERO3 = 0,
};

enum class AS : std::int32_t {
    ZERO4 = 0,
};

enum class BREAK : std::int32_t {
    ZERO5 = 0,
};

enum class CALLABLE : std::int32_t {
    ZERO6 = 0,
};

enum class CASE : std::int32_t {
    ZERO7 = 0,
};

enum class CATCH : std::int32_t {
    ZERO8 = 0,
};

enum class CLASS : std::int32_t {
    ZERO9 = 0,
};

enum class CLONE : std::int32_t {
    ZERO10 = 0,
};

enum class CONST : std::int32_t {
    ZERO11 = 0,
};

enum class CONTINUE : std::int32_t {
    ZERO12 = 0,
};

enum class DECLARE : std::int32_t {
    ZERO13 = 0,
};

enum class DEFAULT : std::int32_t {
    ZERO14 = 0,
};

enum class DIE : std::int32_t {
    ZERO15 = 0,
};

enum class DO : std::int32_t {
    ZERO16 = 0,
};

enum class ECHO : std::int32_t {
    ZERO17 = 0,
};

enum class ELSE : std::int32_t {
    ZERO18 = 0,
};

enum class ELSEIF : std::int32_t {
    ZERO19 = 0,
};

enum class EMPTY : std::int32_t {
    ZERO20 = 0,
};

enum class ENDDECLARE : std::int32_t {
    ZERO21 = 0,
};

enum class ENDFOR : std::int32_t {
    ZERO22 = 0,
};

enum class ENDFOREACH : std::int32_t {
    ZERO23 = 0,
};

enum class ENDIF : std::int32_t {
    ZERO24 = 0,
};

enum class ENDSWITCH : std::int32_t {
    ZERO25 = 0,
};

enum class ENDWHILE : std::int32_t {
    ZERO26 = 0,
};

enum class EVAL : std::int32_t {
    ZERO27 = 0,
};

enum class EXIT : std::int32_t {
    ZERO28 = 0,
};

enum class EXTENDS : std::int32_t {
    ZERO29 = 0,
};

enum class FINAL : std::int32_t {
    ZERO30 = 0,
};

enum class FINALLY : std::int32_t {
    ZERO31 = 0,
};

enum class FN : std::int32_t {
    ZERO32 = 0,
};

enum class FOR : std::int32_t {
    ZERO33 = 0,
};

enum class FOREACH : std::int32_t {
    ZERO34 = 0,
};

enum class FUNCTION : std::int32_t {
    ZERO35 = 0,
};

enum class GLOBAL : std::int32_t {
    ZERO36 = 0,
};

enum class GOTO : std::int32_t {
    ZERO37 = 0,
};

enum class IF : std::int32_t {
    ZERO38 = 0,
};

enum class IMPLEMENTS : std::int32_t {
    ZERO39 = 0,
};

enum class INCLUDE : std::int32_t {
    ZERO40 = 0,
};

enum class INCLUDE_ONCE : std::int32_t {
    ZERO41 = 0,
};

enum class INSTANCEOF : std::int32_t {
    ZERO42 = 0,
};

enum class INSTEADOF : std::int32_t {
    ZERO43 = 0,
};

enum class INTERFACE : std::int32_t {
    ZERO44 = 0,
};

enum class ISSET : std::int32_t {
    ZERO45 = 0,
};

enum class LIST : std::int32_t {
    ZERO46 = 0,
};

enum class MATCH : std::int32_t {
    ZERO47 = 0,
};

enum class NAMESPACE : std::int32_t {
    ZERO48 = 0,
};

enum class NEW : std::int32_t {
    ZERO49 = 0,
};

enum class OR : std::int32_t {
    ZERO50 = 0,
};

enum class PARENT : std::int32_t {
    ZERO78 = 0,
};

enum class PRINT : std::int32_t {
    ZERO51 = 0,
};

enum class PRIVATE : std::int32_t {
    ZERO52 = 0,
};

enum class PROTECTED : std::int32_t {
    ZERO53 = 0,
};

enum class PUBLIC : std::int32_t {
    ZERO54 = 0,
};

enum class READONLY : std::int32_t {
    ZERO80 = 0,
};

enum class REQUIRE : std::int32_t {
    ZERO55 = 0,
};

enum class REQUIRE_ONCE : std::int32_t {
    ZERO56 = 0,
};

enum class RETURN : std::int32_t {
    ZERO57 = 0,
};

enum class SELF : std::int32_t {
    ZERO79 = 0,
};

enum class STATIC : std::int32_t {
    ZERO58 = 0,
};

enum class SWITCH : std::int32_t {
    ZERO59 = 0,
};

enum class THROW : std::int32_t {
    ZERO60 = 0,
};

enum class TRAIT : std::int32_t {
    ZERO61 = 0,
};

enum class TRY : std::int32_t {
    ZERO62 = 0,
};

enum class UNSET : std::int32_t {
    ZERO63 = 0,
};

enum class USE : std::int32_t {
    ZERO64 = 0,
};

enum class VAR : std::int32_t {
    ZERO65 = 0,
};

enum class WHILE : std::int32_t {
    ZERO66 = 0,
};

enum class XOR : std::int32_t {
    ZERO67 = 0,
};

enum class YIELD : std::int32_t {
    ZERO68 = 0,
};

enum class INT : std::int32_t {
    ZERO69 = 0,
};

enum class FLOAT : std::int32_t {
    ZERO70 = 0,
};

enum class BOOL : std::int32_t {
    ZERO71 = 0,
};

enum class STRING : std::int32_t {
    ZERO72 = 0,
};

enum class TRUE : std::int32_t {
    ZERO73 = 0,
};

enum class FALSE : std::int32_t {
    ZERO74 = 0,
};

enum class NULL_ : std::int32_t {
    ZERO75 = 0,
};

enum class VOID : std::int32_t {
    ZERO76 = 0,
};

enum class ITERABLE : std::int32_t {
    ZERO77 = 0,
};

} // namespace upper_enum
