// Generated by protoc-gen-proto23 -- DO NOT EDIT
// Source: test_reserved_enum_value_lower.proto

#pragma once

#include <proto23/proto23.h>

#include <cstddef>
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>

namespace lower_enum_value {

enum class NotAllowed : std::int32_t {
    abstract = 0,
    and_ = 1,
    array = 2,
    as = 3,
    break_ = 4,
    callable = 5,
    case_ = 6,
    catch_ = 7,
    class_ = 8,
    clone = 9,
    const_ = 10,
    continue_ = 11,
    declare = 12,
    default_ = 13,
    die = 14,
    do_ = 15,
    echo = 16,
    else_ = 17,
    elseif = 18,
    empty = 19,
    enddeclare = 20,
    endfor = 21,
    endforeach = 22,
    endif = 23,
    endswitch = 24,
    endwhile = 25,
    eval = 26,
    exit = 27,
    extends = 28,
    final = 29,
    finally = 30,
    fn = 31,
    for_ = 32,
    foreach = 33,
    function = 34,
    global = 35,
    goto_ = 36,
    if_ = 37,
    implements = 38,
    include = 39,
    include_once = 40,
    instanceof = 41,
    insteadof = 42,
    interface = 43,
    isset = 44,
    list = 45,
    match = 46,
    namespace_ = 47,
    new_ = 48,
    or_ = 49,
    parent = 77,
    print = 50,
    private_ = 51,
    protected_ = 52,
    public_ = 53,
    readonly = 79,
    require = 54,
    require_once = 55,
    return_ = 56,
    self = 78,
    static_ = 57,
    switch_ = 58,
    throw_ = 59,
    trait = 60,
    try_ = 61,
    unset = 62,
    use = 63,
    var = 64,
    while_ = 65,
    xor_ = 66,
    yield = 67,
    int_ = 68,
    float_ = 69,
    bool_ = 70,
    string = 71,
    true_ = 72,
    false_ = 73,
    null = 74,
    void_ = 75,
    iterable = 76,
};

} // namespace lower_enum_value
