// Generated by protoc-gen-proto23 -- DO NOT EDIT
// Source: test_messages_proto3.proto

#pragma once

#include <proto23/proto23.h>

#include <cstddef>
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>

#include "google/protobuf/any.proto23.h"
#include "google/protobuf/duration.proto23.h"
#include "google/protobuf/empty.proto23.h"
#include "google/protobuf/field_mask.proto23.h"
#include "google/protobuf/struct.proto23.h"
#include "google/protobuf/timestamp.proto23.h"
#include "google/protobuf/wrappers.proto23.h"

namespace protobuf_test_messages::proto3 {

struct TestAllTypesProto3;
struct ForeignMessage;
struct NullHypothesisProto3;
struct EnumOnlyProto3;

enum class ForeignEnum : std::int32_t {
    FOREIGN_FOO = 0,
    FOREIGN_BAR = 1,
    FOREIGN_BAZ = 2,
};

struct TestAllTypesProto3 {
    enum class NestedEnum : std::int32_t {
        FOO = 0,
        BAR = 1,
        BAZ = 2,
        NEG = -1,
    };

    enum class AliasedEnum : std::int32_t {
        ALIAS_FOO = 0,
        ALIAS_BAR = 1,
        ALIAS_BAZ = 2,
        MOO = 2,
        moo = 2,
        bAz = 2,
    };

    struct NestedMessage {
        proto23::int32 a{};
        std::unique_ptr<TestAllTypesProto3> corecursive;

        using Model = proto23::Fields<
            proto23::Field<&NestedMessage::a, 1>,
            proto23::Field<&NestedMessage::corecursive, 2>>;
    };

    proto23::int32 optional_int32{};
    proto23::int64 optional_int64{};
    std::uint32_t optional_uint32{};
    std::uint64_t optional_uint64{};
    std::int32_t optional_sint32{};
    std::int64_t optional_sint64{};
    proto23::fixed32 optional_fixed32{};
    proto23::fixed64 optional_fixed64{};
    proto23::sfixed32 optional_sfixed32{};
    proto23::sfixed64 optional_sfixed64{};
    float optional_float{};
    double optional_double{};
    bool optional_bool{};
    std::string optional_string{};
    std::vector<std::byte> optional_bytes{};
    TestAllTypesProto3::NestedMessage optional_nested_message;
    std::unique_ptr<ForeignMessage> optional_foreign_message;
    TestAllTypesProto3::NestedEnum optional_nested_enum{};
    ForeignEnum optional_foreign_enum{};
    TestAllTypesProto3::AliasedEnum optional_aliased_enum{};
    std::string optional_string_piece{};
    std::string optional_cord{};
    std::unique_ptr<TestAllTypesProto3> recursive_message;
    std::vector<proto23::int32> repeated_int32{};
    std::vector<proto23::int64> repeated_int64{};
    std::vector<std::uint32_t> repeated_uint32{};
    std::vector<std::uint64_t> repeated_uint64{};
    std::vector<std::int32_t> repeated_sint32{};
    std::vector<std::int64_t> repeated_sint64{};
    std::vector<proto23::fixed32> repeated_fixed32{};
    std::vector<proto23::fixed64> repeated_fixed64{};
    std::vector<proto23::sfixed32> repeated_sfixed32{};
    std::vector<proto23::sfixed64> repeated_sfixed64{};
    std::vector<float> repeated_float{};
    std::vector<double> repeated_double{};
    std::vector<bool> repeated_bool{};
    std::vector<std::string> repeated_string{};
    std::vector<std::vector<std::byte>> repeated_bytes{};
    std::vector<TestAllTypesProto3::NestedMessage> repeated_nested_message;
    std::vector<ForeignMessage> repeated_foreign_message;
    std::vector<TestAllTypesProto3::NestedEnum> repeated_nested_enum{};
    std::vector<ForeignEnum> repeated_foreign_enum{};
    std::vector<std::string> repeated_string_piece{};
    std::vector<std::string> repeated_cord{};
    std::vector<proto23::int32> packed_int32{};
    std::vector<proto23::int64> packed_int64{};
    std::vector<std::uint32_t> packed_uint32{};
    std::vector<std::uint64_t> packed_uint64{};
    std::vector<std::int32_t> packed_sint32{};
    std::vector<std::int64_t> packed_sint64{};
    std::vector<proto23::fixed32> packed_fixed32{};
    std::vector<proto23::fixed64> packed_fixed64{};
    std::vector<proto23::sfixed32> packed_sfixed32{};
    std::vector<proto23::sfixed64> packed_sfixed64{};
    std::vector<float> packed_float{};
    std::vector<double> packed_double{};
    std::vector<bool> packed_bool{};
    std::vector<TestAllTypesProto3::NestedEnum> packed_nested_enum{};
    std::vector<proto23::int32> unpacked_int32{};
    std::vector<proto23::int64> unpacked_int64{};
    std::vector<std::uint32_t> unpacked_uint32{};
    std::vector<std::uint64_t> unpacked_uint64{};
    std::vector<std::int32_t> unpacked_sint32{};
    std::vector<std::int64_t> unpacked_sint64{};
    std::vector<proto23::fixed32> unpacked_fixed32{};
    std::vector<proto23::fixed64> unpacked_fixed64{};
    std::vector<proto23::sfixed32> unpacked_sfixed32{};
    std::vector<proto23::sfixed64> unpacked_sfixed64{};
    std::vector<float> unpacked_float{};
    std::vector<double> unpacked_double{};
    std::vector<bool> unpacked_bool{};
    std::vector<TestAllTypesProto3::NestedEnum> unpacked_nested_enum{};
    std::map<proto23::int32, proto23::int32> map_int32_int32{};
    std::map<proto23::int64, proto23::int64> map_int64_int64{};
    std::map<std::uint32_t, std::uint32_t> map_uint32_uint32{};
    std::map<std::uint64_t, std::uint64_t> map_uint64_uint64{};
    std::map<std::int32_t, std::int32_t> map_sint32_sint32{};
    std::map<std::int64_t, std::int64_t> map_sint64_sint64{};
    std::map<proto23::fixed32, proto23::fixed32> map_fixed32_fixed32{};
    std::map<proto23::fixed64, proto23::fixed64> map_fixed64_fixed64{};
    std::map<proto23::sfixed32, proto23::sfixed32> map_sfixed32_sfixed32{};
    std::map<proto23::sfixed64, proto23::sfixed64> map_sfixed64_sfixed64{};
    std::map<proto23::int32, float> map_int32_float{};
    std::map<proto23::int32, double> map_int32_double{};
    std::map<bool, bool> map_bool_bool{};
    std::map<std::string, std::string> map_string_string{};
    std::map<std::string, std::vector<std::byte>> map_string_bytes{};
    std::map<std::string, TestAllTypesProto3::NestedMessage> map_string_nested_message{};
    std::map<std::string, ForeignMessage> map_string_foreign_message{};
    std::map<std::string, TestAllTypesProto3::NestedEnum> map_string_nested_enum{};
    std::map<std::string, ForeignEnum> map_string_foreign_enum{};
    std::variant<std::uint32_t, TestAllTypesProto3::NestedMessage, std::string, std::vector<std::byte>, bool, std::uint64_t, float, double, TestAllTypesProto3::NestedEnum, google::protobuf::NullValue> oneof_field;
    std::unique_ptr<google::protobuf::BoolValue> optional_bool_wrapper{};
    std::unique_ptr<google::protobuf::Int32Value> optional_int32_wrapper{};
    std::unique_ptr<google::protobuf::Int64Value> optional_int64_wrapper{};
    std::unique_ptr<google::protobuf::UInt32Value> optional_uint32_wrapper{};
    std::unique_ptr<google::protobuf::UInt64Value> optional_uint64_wrapper{};
    std::unique_ptr<google::protobuf::FloatValue> optional_float_wrapper{};
    std::unique_ptr<google::protobuf::DoubleValue> optional_double_wrapper{};
    std::unique_ptr<google::protobuf::StringValue> optional_string_wrapper{};
    std::unique_ptr<google::protobuf::BytesValue> optional_bytes_wrapper{};
    std::vector<google::protobuf::BoolValue> repeated_bool_wrapper{};
    std::vector<google::protobuf::Int32Value> repeated_int32_wrapper{};
    std::vector<google::protobuf::Int64Value> repeated_int64_wrapper{};
    std::vector<google::protobuf::UInt32Value> repeated_uint32_wrapper{};
    std::vector<google::protobuf::UInt64Value> repeated_uint64_wrapper{};
    std::vector<google::protobuf::FloatValue> repeated_float_wrapper{};
    std::vector<google::protobuf::DoubleValue> repeated_double_wrapper{};
    std::vector<google::protobuf::StringValue> repeated_string_wrapper{};
    std::vector<google::protobuf::BytesValue> repeated_bytes_wrapper{};
    std::unique_ptr<google::protobuf::Duration> optional_duration{};
    std::unique_ptr<google::protobuf::Timestamp> optional_timestamp{};
    std::unique_ptr<google::protobuf::FieldMask> optional_field_mask{};
    std::unique_ptr<google::protobuf::Struct> optional_struct{};
    std::unique_ptr<google::protobuf::Any> optional_any{};
    std::unique_ptr<google::protobuf::Value> optional_value{};
    google::protobuf::NullValue optional_null_value{};
    std::unique_ptr<google::protobuf::Empty> optional_empty{};
    std::vector<google::protobuf::Duration> repeated_duration{};
    std::vector<google::protobuf::Timestamp> repeated_timestamp{};
    std::vector<google::protobuf::FieldMask> repeated_fieldmask{};
    std::vector<google::protobuf::Struct> repeated_struct{};
    std::vector<google::protobuf::Any> repeated_any{};
    std::vector<google::protobuf::Value> repeated_value{};
    std::vector<google::protobuf::ListValue> repeated_list_value{};
    std::vector<google::protobuf::Empty> repeated_empty{};
    proto23::int32 fieldname1{};
    proto23::int32 field_name2{};
    proto23::int32 _field_name3{};
    proto23::int32 field__name4_{};
    proto23::int32 field0name5{};
    proto23::int32 field_0_name6{};
    proto23::int32 fieldName7{};
    proto23::int32 FieldName8{};
    proto23::int32 field_Name9{};
    proto23::int32 Field_Name10{};
    proto23::int32 FIELD_NAME11{};
    proto23::int32 FIELD_name12{};
    proto23::int32 __field_name13{};
    proto23::int32 __Field_name14{};
    proto23::int32 field__name15{};
    proto23::int32 field__Name16{};
    proto23::int32 field_name17__{};
    proto23::int32 Field_name18__{};

    using Model = proto23::Fields<
        proto23::Field<&TestAllTypesProto3::optional_int32, 1>,
        proto23::Field<&TestAllTypesProto3::optional_int64, 2>,
        proto23::Field<&TestAllTypesProto3::optional_uint32, 3>,
        proto23::Field<&TestAllTypesProto3::optional_uint64, 4>,
        proto23::Field<&TestAllTypesProto3::optional_sint32, 5>,
        proto23::Field<&TestAllTypesProto3::optional_sint64, 6>,
        proto23::Field<&TestAllTypesProto3::optional_fixed32, 7>,
        proto23::Field<&TestAllTypesProto3::optional_fixed64, 8>,
        proto23::Field<&TestAllTypesProto3::optional_sfixed32, 9>,
        proto23::Field<&TestAllTypesProto3::optional_sfixed64, 10>,
        proto23::Field<&TestAllTypesProto3::optional_float, 11>,
        proto23::Field<&TestAllTypesProto3::optional_double, 12>,
        proto23::Field<&TestAllTypesProto3::optional_bool, 13>,
        proto23::Field<&TestAllTypesProto3::optional_string, 14>,
        proto23::Field<&TestAllTypesProto3::optional_bytes, 15>,
        proto23::Field<&TestAllTypesProto3::optional_nested_message, 18>,
        proto23::Field<&TestAllTypesProto3::optional_foreign_message, 19>,
        proto23::Field<&TestAllTypesProto3::optional_nested_enum, 21>,
        proto23::Field<&TestAllTypesProto3::optional_foreign_enum, 22>,
        proto23::Field<&TestAllTypesProto3::optional_aliased_enum, 23>,
        proto23::Field<&TestAllTypesProto3::optional_string_piece, 24>,
        proto23::Field<&TestAllTypesProto3::optional_cord, 25>,
        proto23::Field<&TestAllTypesProto3::recursive_message, 27>,
        proto23::Field<&TestAllTypesProto3::repeated_int32, 31>,
        proto23::Field<&TestAllTypesProto3::repeated_int64, 32>,
        proto23::Field<&TestAllTypesProto3::repeated_uint32, 33>,
        proto23::Field<&TestAllTypesProto3::repeated_uint64, 34>,
        proto23::Field<&TestAllTypesProto3::repeated_sint32, 35>,
        proto23::Field<&TestAllTypesProto3::repeated_sint64, 36>,
        proto23::Field<&TestAllTypesProto3::repeated_fixed32, 37>,
        proto23::Field<&TestAllTypesProto3::repeated_fixed64, 38>,
        proto23::Field<&TestAllTypesProto3::repeated_sfixed32, 39>,
        proto23::Field<&TestAllTypesProto3::repeated_sfixed64, 40>,
        proto23::Field<&TestAllTypesProto3::repeated_float, 41>,
        proto23::Field<&TestAllTypesProto3::repeated_double, 42>,
        proto23::Field<&TestAllTypesProto3::repeated_bool, 43>,
        proto23::Field<&TestAllTypesProto3::repeated_string, 44>,
        proto23::Field<&TestAllTypesProto3::repeated_bytes, 45>,
        proto23::Field<&TestAllTypesProto3::repeated_nested_message, 48>,
        proto23::Field<&TestAllTypesProto3::repeated_foreign_message, 49>,
        proto23::Field<&TestAllTypesProto3::repeated_nested_enum, 51>,
        proto23::Field<&TestAllTypesProto3::repeated_foreign_enum, 52>,
        proto23::Field<&TestAllTypesProto3::repeated_string_piece, 54, proto23::packed_t::no>,
        proto23::Field<&TestAllTypesProto3::repeated_cord, 55, proto23::packed_t::no>,
        proto23::Field<&TestAllTypesProto3::packed_int32, 75>,
        proto23::Field<&TestAllTypesProto3::packed_int64, 76>,
        proto23::Field<&TestAllTypesProto3::packed_uint32, 77>,
        proto23::Field<&TestAllTypesProto3::packed_uint64, 78>,
        proto23::Field<&TestAllTypesProto3::packed_sint32, 79>,
        proto23::Field<&TestAllTypesProto3::packed_sint64, 80>,
        proto23::Field<&TestAllTypesProto3::packed_fixed32, 81>,
        proto23::Field<&TestAllTypesProto3::packed_fixed64, 82>,
        proto23::Field<&TestAllTypesProto3::packed_sfixed32, 83>,
        proto23::Field<&TestAllTypesProto3::packed_sfixed64, 84>,
        proto23::Field<&TestAllTypesProto3::packed_float, 85>,
        proto23::Field<&TestAllTypesProto3::packed_double, 86>,
        proto23::Field<&TestAllTypesProto3::packed_bool, 87>,
        proto23::Field<&TestAllTypesProto3::packed_nested_enum, 88>,
        proto23::Field<&TestAllTypesProto3::unpacked_int32, 89, proto23::packed_t::no>,
        proto23::Field<&TestAllTypesProto3::unpacked_int64, 90, proto23::packed_t::no>,
        proto23::Field<&TestAllTypesProto3::unpacked_uint32, 91, proto23::packed_t::no>,
        proto23::Field<&TestAllTypesProto3::unpacked_uint64, 92, proto23::packed_t::no>,
        proto23::Field<&TestAllTypesProto3::unpacked_sint32, 93, proto23::packed_t::no>,
        proto23::Field<&TestAllTypesProto3::unpacked_sint64, 94, proto23::packed_t::no>,
        proto23::Field<&TestAllTypesProto3::unpacked_fixed32, 95, proto23::packed_t::no>,
        proto23::Field<&TestAllTypesProto3::unpacked_fixed64, 96, proto23::packed_t::no>,
        proto23::Field<&TestAllTypesProto3::unpacked_sfixed32, 97, proto23::packed_t::no>,
        proto23::Field<&TestAllTypesProto3::unpacked_sfixed64, 98, proto23::packed_t::no>,
        proto23::Field<&TestAllTypesProto3::unpacked_float, 99, proto23::packed_t::no>,
        proto23::Field<&TestAllTypesProto3::unpacked_double, 100, proto23::packed_t::no>,
        proto23::Field<&TestAllTypesProto3::unpacked_bool, 101, proto23::packed_t::no>,
        proto23::Field<&TestAllTypesProto3::unpacked_nested_enum, 102, proto23::packed_t::no>,
        proto23::Field<&TestAllTypesProto3::map_int32_int32, 56>,
        proto23::Field<&TestAllTypesProto3::map_int64_int64, 57>,
        proto23::Field<&TestAllTypesProto3::map_uint32_uint32, 58>,
        proto23::Field<&TestAllTypesProto3::map_uint64_uint64, 59>,
        proto23::Field<&TestAllTypesProto3::map_sint32_sint32, 60>,
        proto23::Field<&TestAllTypesProto3::map_sint64_sint64, 61>,
        proto23::Field<&TestAllTypesProto3::map_fixed32_fixed32, 62>,
        proto23::Field<&TestAllTypesProto3::map_fixed64_fixed64, 63>,
        proto23::Field<&TestAllTypesProto3::map_sfixed32_sfixed32, 64>,
        proto23::Field<&TestAllTypesProto3::map_sfixed64_sfixed64, 65>,
        proto23::Field<&TestAllTypesProto3::map_int32_float, 66>,
        proto23::Field<&TestAllTypesProto3::map_int32_double, 67>,
        proto23::Field<&TestAllTypesProto3::map_bool_bool, 68>,
        proto23::Field<&TestAllTypesProto3::map_string_string, 69>,
        proto23::Field<&TestAllTypesProto3::map_string_bytes, 70>,
        proto23::Field<&TestAllTypesProto3::map_string_nested_message, 71>,
        proto23::Field<&TestAllTypesProto3::map_string_foreign_message, 72>,
        proto23::Field<&TestAllTypesProto3::map_string_nested_enum, 73>,
        proto23::Field<&TestAllTypesProto3::map_string_foreign_enum, 74>,
        proto23::OneOf<&TestAllTypesProto3::oneof_field, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120>,
        proto23::Field<&TestAllTypesProto3::optional_bool_wrapper, 201>,
        proto23::Field<&TestAllTypesProto3::optional_int32_wrapper, 202>,
        proto23::Field<&TestAllTypesProto3::optional_int64_wrapper, 203>,
        proto23::Field<&TestAllTypesProto3::optional_uint32_wrapper, 204>,
        proto23::Field<&TestAllTypesProto3::optional_uint64_wrapper, 205>,
        proto23::Field<&TestAllTypesProto3::optional_float_wrapper, 206>,
        proto23::Field<&TestAllTypesProto3::optional_double_wrapper, 207>,
        proto23::Field<&TestAllTypesProto3::optional_string_wrapper, 208>,
        proto23::Field<&TestAllTypesProto3::optional_bytes_wrapper, 209>,
        proto23::Field<&TestAllTypesProto3::repeated_bool_wrapper, 211>,
        proto23::Field<&TestAllTypesProto3::repeated_int32_wrapper, 212>,
        proto23::Field<&TestAllTypesProto3::repeated_int64_wrapper, 213>,
        proto23::Field<&TestAllTypesProto3::repeated_uint32_wrapper, 214>,
        proto23::Field<&TestAllTypesProto3::repeated_uint64_wrapper, 215>,
        proto23::Field<&TestAllTypesProto3::repeated_float_wrapper, 216>,
        proto23::Field<&TestAllTypesProto3::repeated_double_wrapper, 217>,
        proto23::Field<&TestAllTypesProto3::repeated_string_wrapper, 218>,
        proto23::Field<&TestAllTypesProto3::repeated_bytes_wrapper, 219>,
        proto23::Field<&TestAllTypesProto3::optional_duration, 301>,
        proto23::Field<&TestAllTypesProto3::optional_timestamp, 302>,
        proto23::Field<&TestAllTypesProto3::optional_field_mask, 303>,
        proto23::Field<&TestAllTypesProto3::optional_struct, 304>,
        proto23::Field<&TestAllTypesProto3::optional_any, 305>,
        proto23::Field<&TestAllTypesProto3::optional_value, 306>,
        proto23::Field<&TestAllTypesProto3::optional_null_value, 307>,
        proto23::Field<&TestAllTypesProto3::optional_empty, 308>,
        proto23::Field<&TestAllTypesProto3::repeated_duration, 311>,
        proto23::Field<&TestAllTypesProto3::repeated_timestamp, 312>,
        proto23::Field<&TestAllTypesProto3::repeated_fieldmask, 313>,
        proto23::Field<&TestAllTypesProto3::repeated_struct, 324>,
        proto23::Field<&TestAllTypesProto3::repeated_any, 315>,
        proto23::Field<&TestAllTypesProto3::repeated_value, 316>,
        proto23::Field<&TestAllTypesProto3::repeated_list_value, 317>,
        proto23::Field<&TestAllTypesProto3::repeated_empty, 318>,
        proto23::Field<&TestAllTypesProto3::fieldname1, 401>,
        proto23::Field<&TestAllTypesProto3::field_name2, 402>,
        proto23::Field<&TestAllTypesProto3::_field_name3, 403>,
        proto23::Field<&TestAllTypesProto3::field__name4_, 404>,
        proto23::Field<&TestAllTypesProto3::field0name5, 405>,
        proto23::Field<&TestAllTypesProto3::field_0_name6, 406>,
        proto23::Field<&TestAllTypesProto3::fieldName7, 407>,
        proto23::Field<&TestAllTypesProto3::FieldName8, 408>,
        proto23::Field<&TestAllTypesProto3::field_Name9, 409>,
        proto23::Field<&TestAllTypesProto3::Field_Name10, 410>,
        proto23::Field<&TestAllTypesProto3::FIELD_NAME11, 411>,
        proto23::Field<&TestAllTypesProto3::FIELD_name12, 412>,
        proto23::Field<&TestAllTypesProto3::__field_name13, 413>,
        proto23::Field<&TestAllTypesProto3::__Field_name14, 414>,
        proto23::Field<&TestAllTypesProto3::field__name15, 415>,
        proto23::Field<&TestAllTypesProto3::field__Name16, 416>,
        proto23::Field<&TestAllTypesProto3::field_name17__, 417>,
        proto23::Field<&TestAllTypesProto3::Field_name18__, 418>>;
};

struct ForeignMessage {
    proto23::int32 c{};

    using Model = proto23::Fields<
        proto23::Field<&ForeignMessage::c, 1>>;
};

struct NullHypothesisProto3 {
    // This message has no fields
};

struct EnumOnlyProto3 {
    enum class Bool : std::int32_t {
        kFalse = 0,
        kTrue = 1,
    };

    // This message has no fields
};

} // namespace protobuf_test_messages::proto3
