// Generated by protoc-gen-proto23 -- DO NOT EDIT
// Source: test_reserved_enum_upper.proto

#pragma once

#include <proto23/enum_traits.h>
#include <proto23/proto23.h>

#include <cstddef>
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>

namespace upper_enum {

enum class ABSTRACT : std::int32_t {
    ZERO1 = 0,
};

enum class AND : std::int32_t {
    ZERO2 = 0,
};

enum class ARRAY : std::int32_t {
    ZERO3 = 0,
};

enum class AS : std::int32_t {
    ZERO4 = 0,
};

enum class BREAK : std::int32_t {
    ZERO5 = 0,
};

enum class CALLABLE : std::int32_t {
    ZERO6 = 0,
};

enum class CASE : std::int32_t {
    ZERO7 = 0,
};

enum class CATCH : std::int32_t {
    ZERO8 = 0,
};

enum class CLASS : std::int32_t {
    ZERO9 = 0,
};

enum class CLONE : std::int32_t {
    ZERO10 = 0,
};

enum class CONST : std::int32_t {
    ZERO11 = 0,
};

enum class CONTINUE : std::int32_t {
    ZERO12 = 0,
};

enum class DECLARE : std::int32_t {
    ZERO13 = 0,
};

enum class DEFAULT : std::int32_t {
    ZERO14 = 0,
};

enum class DIE : std::int32_t {
    ZERO15 = 0,
};

enum class DO : std::int32_t {
    ZERO16 = 0,
};

enum class ECHO : std::int32_t {
    ZERO17 = 0,
};

enum class ELSE : std::int32_t {
    ZERO18 = 0,
};

enum class ELSEIF : std::int32_t {
    ZERO19 = 0,
};

enum class EMPTY : std::int32_t {
    ZERO20 = 0,
};

enum class ENDDECLARE : std::int32_t {
    ZERO21 = 0,
};

enum class ENDFOR : std::int32_t {
    ZERO22 = 0,
};

enum class ENDFOREACH : std::int32_t {
    ZERO23 = 0,
};

enum class ENDIF : std::int32_t {
    ZERO24 = 0,
};

enum class ENDSWITCH : std::int32_t {
    ZERO25 = 0,
};

enum class ENDWHILE : std::int32_t {
    ZERO26 = 0,
};

enum class EVAL : std::int32_t {
    ZERO27 = 0,
};

enum class EXIT : std::int32_t {
    ZERO28 = 0,
};

enum class EXTENDS : std::int32_t {
    ZERO29 = 0,
};

enum class FINAL : std::int32_t {
    ZERO30 = 0,
};

enum class FINALLY : std::int32_t {
    ZERO31 = 0,
};

enum class FN : std::int32_t {
    ZERO32 = 0,
};

enum class FOR : std::int32_t {
    ZERO33 = 0,
};

enum class FOREACH : std::int32_t {
    ZERO34 = 0,
};

enum class FUNCTION : std::int32_t {
    ZERO35 = 0,
};

enum class GLOBAL : std::int32_t {
    ZERO36 = 0,
};

enum class GOTO : std::int32_t {
    ZERO37 = 0,
};

enum class IF : std::int32_t {
    ZERO38 = 0,
};

enum class IMPLEMENTS : std::int32_t {
    ZERO39 = 0,
};

enum class INCLUDE : std::int32_t {
    ZERO40 = 0,
};

enum class INCLUDE_ONCE : std::int32_t {
    ZERO41 = 0,
};

enum class INSTANCEOF : std::int32_t {
    ZERO42 = 0,
};

enum class INSTEADOF : std::int32_t {
    ZERO43 = 0,
};

enum class INTERFACE : std::int32_t {
    ZERO44 = 0,
};

enum class ISSET : std::int32_t {
    ZERO45 = 0,
};

enum class LIST : std::int32_t {
    ZERO46 = 0,
};

enum class MATCH : std::int32_t {
    ZERO47 = 0,
};

enum class NAMESPACE : std::int32_t {
    ZERO48 = 0,
};

enum class NEW : std::int32_t {
    ZERO49 = 0,
};

enum class OR : std::int32_t {
    ZERO50 = 0,
};

enum class PARENT : std::int32_t {
    ZERO78 = 0,
};

enum class PRINT : std::int32_t {
    ZERO51 = 0,
};

enum class PRIVATE : std::int32_t {
    ZERO52 = 0,
};

enum class PROTECTED : std::int32_t {
    ZERO53 = 0,
};

enum class PUBLIC : std::int32_t {
    ZERO54 = 0,
};

enum class READONLY : std::int32_t {
    ZERO80 = 0,
};

enum class REQUIRE : std::int32_t {
    ZERO55 = 0,
};

enum class REQUIRE_ONCE : std::int32_t {
    ZERO56 = 0,
};

enum class RETURN : std::int32_t {
    ZERO57 = 0,
};

enum class SELF : std::int32_t {
    ZERO79 = 0,
};

enum class STATIC : std::int32_t {
    ZERO58 = 0,
};

enum class SWITCH : std::int32_t {
    ZERO59 = 0,
};

enum class THROW : std::int32_t {
    ZERO60 = 0,
};

enum class TRAIT : std::int32_t {
    ZERO61 = 0,
};

enum class TRY : std::int32_t {
    ZERO62 = 0,
};

enum class UNSET : std::int32_t {
    ZERO63 = 0,
};

enum class USE : std::int32_t {
    ZERO64 = 0,
};

enum class VAR : std::int32_t {
    ZERO65 = 0,
};

enum class WHILE : std::int32_t {
    ZERO66 = 0,
};

enum class XOR : std::int32_t {
    ZERO67 = 0,
};

enum class YIELD : std::int32_t {
    ZERO68 = 0,
};

enum class INT : std::int32_t {
    ZERO69 = 0,
};

enum class FLOAT : std::int32_t {
    ZERO70 = 0,
};

enum class BOOL : std::int32_t {
    ZERO71 = 0,
};

enum class STRING : std::int32_t {
    ZERO72 = 0,
};

enum class TRUE : std::int32_t {
    ZERO73 = 0,
};

enum class FALSE : std::int32_t {
    ZERO74 = 0,
};

enum class NULL_ : std::int32_t {
    ZERO75 = 0,
};

enum class VOID : std::int32_t {
    ZERO76 = 0,
};

enum class ITERABLE : std::int32_t {
    ZERO77 = 0,
};

} // namespace upper_enum

namespace proto23 {

template<>
struct enum_traits<upper_enum::ABSTRACT> : 
    proto23::detail::make_enum_traits<upper_enum::ABSTRACT,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::AND> : 
    proto23::detail::make_enum_traits<upper_enum::AND,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::ARRAY> : 
    proto23::detail::make_enum_traits<upper_enum::ARRAY,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::AS> : 
    proto23::detail::make_enum_traits<upper_enum::AS,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::BREAK> : 
    proto23::detail::make_enum_traits<upper_enum::BREAK,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::CALLABLE> : 
    proto23::detail::make_enum_traits<upper_enum::CALLABLE,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::CASE> : 
    proto23::detail::make_enum_traits<upper_enum::CASE,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::CATCH> : 
    proto23::detail::make_enum_traits<upper_enum::CATCH,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::CLASS> : 
    proto23::detail::make_enum_traits<upper_enum::CLASS,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::CLONE> : 
    proto23::detail::make_enum_traits<upper_enum::CLONE,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::CONST> : 
    proto23::detail::make_enum_traits<upper_enum::CONST,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::CONTINUE> : 
    proto23::detail::make_enum_traits<upper_enum::CONTINUE,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::DECLARE> : 
    proto23::detail::make_enum_traits<upper_enum::DECLARE,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::DEFAULT> : 
    proto23::detail::make_enum_traits<upper_enum::DEFAULT,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::DIE> : 
    proto23::detail::make_enum_traits<upper_enum::DIE,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::DO> : 
    proto23::detail::make_enum_traits<upper_enum::DO,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::ECHO> : 
    proto23::detail::make_enum_traits<upper_enum::ECHO,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::ELSE> : 
    proto23::detail::make_enum_traits<upper_enum::ELSE,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::ELSEIF> : 
    proto23::detail::make_enum_traits<upper_enum::ELSEIF,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::EMPTY> : 
    proto23::detail::make_enum_traits<upper_enum::EMPTY,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::ENDDECLARE> : 
    proto23::detail::make_enum_traits<upper_enum::ENDDECLARE,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::ENDFOR> : 
    proto23::detail::make_enum_traits<upper_enum::ENDFOR,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::ENDFOREACH> : 
    proto23::detail::make_enum_traits<upper_enum::ENDFOREACH,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::ENDIF> : 
    proto23::detail::make_enum_traits<upper_enum::ENDIF,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::ENDSWITCH> : 
    proto23::detail::make_enum_traits<upper_enum::ENDSWITCH,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::ENDWHILE> : 
    proto23::detail::make_enum_traits<upper_enum::ENDWHILE,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::EVAL> : 
    proto23::detail::make_enum_traits<upper_enum::EVAL,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::EXIT> : 
    proto23::detail::make_enum_traits<upper_enum::EXIT,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::EXTENDS> : 
    proto23::detail::make_enum_traits<upper_enum::EXTENDS,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::FINAL> : 
    proto23::detail::make_enum_traits<upper_enum::FINAL,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::FINALLY> : 
    proto23::detail::make_enum_traits<upper_enum::FINALLY,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::FN> : 
    proto23::detail::make_enum_traits<upper_enum::FN,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::FOR> : 
    proto23::detail::make_enum_traits<upper_enum::FOR,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::FOREACH> : 
    proto23::detail::make_enum_traits<upper_enum::FOREACH,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::FUNCTION> : 
    proto23::detail::make_enum_traits<upper_enum::FUNCTION,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::GLOBAL> : 
    proto23::detail::make_enum_traits<upper_enum::GLOBAL,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::GOTO> : 
    proto23::detail::make_enum_traits<upper_enum::GOTO,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::IF> : 
    proto23::detail::make_enum_traits<upper_enum::IF,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::IMPLEMENTS> : 
    proto23::detail::make_enum_traits<upper_enum::IMPLEMENTS,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::INCLUDE> : 
    proto23::detail::make_enum_traits<upper_enum::INCLUDE,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::INCLUDE_ONCE> : 
    proto23::detail::make_enum_traits<upper_enum::INCLUDE_ONCE,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::INSTANCEOF> : 
    proto23::detail::make_enum_traits<upper_enum::INSTANCEOF,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::INSTEADOF> : 
    proto23::detail::make_enum_traits<upper_enum::INSTEADOF,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::INTERFACE> : 
    proto23::detail::make_enum_traits<upper_enum::INTERFACE,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::ISSET> : 
    proto23::detail::make_enum_traits<upper_enum::ISSET,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::LIST> : 
    proto23::detail::make_enum_traits<upper_enum::LIST,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::MATCH> : 
    proto23::detail::make_enum_traits<upper_enum::MATCH,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::NAMESPACE> : 
    proto23::detail::make_enum_traits<upper_enum::NAMESPACE,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::NEW> : 
    proto23::detail::make_enum_traits<upper_enum::NEW,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::OR> : 
    proto23::detail::make_enum_traits<upper_enum::OR,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::PARENT> : 
    proto23::detail::make_enum_traits<upper_enum::PARENT,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::PRINT> : 
    proto23::detail::make_enum_traits<upper_enum::PRINT,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::PRIVATE> : 
    proto23::detail::make_enum_traits<upper_enum::PRIVATE,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::PROTECTED> : 
    proto23::detail::make_enum_traits<upper_enum::PROTECTED,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::PUBLIC> : 
    proto23::detail::make_enum_traits<upper_enum::PUBLIC,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::READONLY> : 
    proto23::detail::make_enum_traits<upper_enum::READONLY,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::REQUIRE> : 
    proto23::detail::make_enum_traits<upper_enum::REQUIRE,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::REQUIRE_ONCE> : 
    proto23::detail::make_enum_traits<upper_enum::REQUIRE_ONCE,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::RETURN> : 
    proto23::detail::make_enum_traits<upper_enum::RETURN,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::SELF> : 
    proto23::detail::make_enum_traits<upper_enum::SELF,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::STATIC> : 
    proto23::detail::make_enum_traits<upper_enum::STATIC,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::SWITCH> : 
    proto23::detail::make_enum_traits<upper_enum::SWITCH,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::THROW> : 
    proto23::detail::make_enum_traits<upper_enum::THROW,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::TRAIT> : 
    proto23::detail::make_enum_traits<upper_enum::TRAIT,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::TRY> : 
    proto23::detail::make_enum_traits<upper_enum::TRY,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::UNSET> : 
    proto23::detail::make_enum_traits<upper_enum::UNSET,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::USE> : 
    proto23::detail::make_enum_traits<upper_enum::USE,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::VAR> : 
    proto23::detail::make_enum_traits<upper_enum::VAR,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::WHILE> : 
    proto23::detail::make_enum_traits<upper_enum::WHILE,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::XOR> : 
    proto23::detail::make_enum_traits<upper_enum::XOR,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::YIELD> : 
    proto23::detail::make_enum_traits<upper_enum::YIELD,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::INT> : 
    proto23::detail::make_enum_traits<upper_enum::INT,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::FLOAT> : 
    proto23::detail::make_enum_traits<upper_enum::FLOAT,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::BOOL> : 
    proto23::detail::make_enum_traits<upper_enum::BOOL,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::STRING> : 
    proto23::detail::make_enum_traits<upper_enum::STRING,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::TRUE> : 
    proto23::detail::make_enum_traits<upper_enum::TRUE,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::FALSE> : 
    proto23::detail::make_enum_traits<upper_enum::FALSE,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::NULL_> : 
    proto23::detail::make_enum_traits<upper_enum::NULL_,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::VOID> : 
    proto23::detail::make_enum_traits<upper_enum::VOID,0,0,1,0U,true>{};
template<>
struct enum_traits<upper_enum::ITERABLE> : 
    proto23::detail::make_enum_traits<upper_enum::ITERABLE,0,0,1,0U,true>{};

}
