// Generated by protoc-gen-proto23 -- DO NOT EDIT
// Source: test_reserved_enum_lower.proto

#pragma once

#include <proto23/proto23.h>

#include <cstddef>
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>

namespace lower_enum {

enum class abstract : std::int32_t {
    ZERO1 = 0,
};

enum class and_ : std::int32_t {
    ZERO2 = 0,
};

enum class array : std::int32_t {
    ZERO3 = 0,
};

enum class as : std::int32_t {
    ZERO4 = 0,
};

enum class break_ : std::int32_t {
    ZERO5 = 0,
};

enum class callable : std::int32_t {
    ZERO6 = 0,
};

enum class case_ : std::int32_t {
    ZERO7 = 0,
};

enum class catch_ : std::int32_t {
    ZERO8 = 0,
};

enum class class_ : std::int32_t {
    ZERO9 = 0,
};

enum class clone : std::int32_t {
    ZERO10 = 0,
};

enum class const_ : std::int32_t {
    ZERO11 = 0,
};

enum class continue_ : std::int32_t {
    ZERO12 = 0,
};

enum class declare : std::int32_t {
    ZERO13 = 0,
};

enum class default_ : std::int32_t {
    ZERO14 = 0,
};

enum class die : std::int32_t {
    ZERO15 = 0,
};

enum class do_ : std::int32_t {
    ZERO16 = 0,
};

enum class echo : std::int32_t {
    ZERO17 = 0,
};

enum class else_ : std::int32_t {
    ZERO18 = 0,
};

enum class elseif : std::int32_t {
    ZERO19 = 0,
};

enum class empty : std::int32_t {
    ZERO20 = 0,
};

enum class enddeclare : std::int32_t {
    ZERO21 = 0,
};

enum class endfor : std::int32_t {
    ZERO22 = 0,
};

enum class endforeach : std::int32_t {
    ZERO23 = 0,
};

enum class endif : std::int32_t {
    ZERO24 = 0,
};

enum class endswitch : std::int32_t {
    ZERO25 = 0,
};

enum class endwhile : std::int32_t {
    ZERO26 = 0,
};

enum class eval : std::int32_t {
    ZERO27 = 0,
};

enum class exit : std::int32_t {
    ZERO28 = 0,
};

enum class extends : std::int32_t {
    ZERO29 = 0,
};

enum class final : std::int32_t {
    ZERO30 = 0,
};

enum class finally : std::int32_t {
    ZERO31 = 0,
};

enum class fn : std::int32_t {
    ZERO32 = 0,
};

enum class for_ : std::int32_t {
    ZERO33 = 0,
};

enum class foreach : std::int32_t {
    ZERO34 = 0,
};

enum class function : std::int32_t {
    ZERO35 = 0,
};

enum class global : std::int32_t {
    ZERO36 = 0,
};

enum class goto_ : std::int32_t {
    ZERO37 = 0,
};

enum class if_ : std::int32_t {
    ZERO38 = 0,
};

enum class implements : std::int32_t {
    ZERO39 = 0,
};

enum class include : std::int32_t {
    ZERO40 = 0,
};

enum class include_once : std::int32_t {
    ZERO41 = 0,
};

enum class instanceof : std::int32_t {
    ZERO42 = 0,
};

enum class insteadof : std::int32_t {
    ZERO43 = 0,
};

enum class interface : std::int32_t {
    ZERO44 = 0,
};

enum class isset : std::int32_t {
    ZERO45 = 0,
};

enum class list : std::int32_t {
    ZERO46 = 0,
};

enum class match : std::int32_t {
    ZERO47 = 0,
};

enum class namespace_ : std::int32_t {
    ZERO48 = 0,
};

enum class new_ : std::int32_t {
    ZERO49 = 0,
};

enum class or_ : std::int32_t {
    ZERO50 = 0,
};

enum class parent : std::int32_t {
    ZERO78 = 0,
};

enum class print : std::int32_t {
    ZERO51 = 0,
};

enum class private_ : std::int32_t {
    ZERO52 = 0,
};

enum class protected_ : std::int32_t {
    ZERO53 = 0,
};

enum class public_ : std::int32_t {
    ZERO54 = 0,
};

enum class readonly : std::int32_t {
    ZERO80 = 0,
};

enum class require : std::int32_t {
    ZERO55 = 0,
};

enum class require_once : std::int32_t {
    ZERO56 = 0,
};

enum class return_ : std::int32_t {
    ZERO57 = 0,
};

enum class self : std::int32_t {
    ZERO79 = 0,
};

enum class static_ : std::int32_t {
    ZERO58 = 0,
};

enum class switch_ : std::int32_t {
    ZERO59 = 0,
};

enum class throw_ : std::int32_t {
    ZERO60 = 0,
};

enum class trait : std::int32_t {
    ZERO61 = 0,
};

enum class try_ : std::int32_t {
    ZERO62 = 0,
};

enum class unset : std::int32_t {
    ZERO63 = 0,
};

enum class use : std::int32_t {
    ZERO64 = 0,
};

enum class var : std::int32_t {
    ZERO65 = 0,
};

enum class while_ : std::int32_t {
    ZERO66 = 0,
};

enum class xor_ : std::int32_t {
    ZERO67 = 0,
};

enum class yield : std::int32_t {
    ZERO68 = 0,
};

enum class int_ : std::int32_t {
    ZERO69 = 0,
};

enum class float_ : std::int32_t {
    ZERO70 = 0,
};

enum class bool_ : std::int32_t {
    ZERO71 = 0,
};

enum class string : std::int32_t {
    ZERO72 = 0,
};

enum class true_ : std::int32_t {
    ZERO73 = 0,
};

enum class false_ : std::int32_t {
    ZERO74 = 0,
};

enum class null : std::int32_t {
    ZERO75 = 0,
};

enum class void_ : std::int32_t {
    ZERO76 = 0,
};

enum class iterable : std::int32_t {
    ZERO77 = 0,
};

} // namespace lower_enum
