// Generated by protoc-gen-proto23 -- DO NOT EDIT
// Source: unittest_runtime_proto3.proto

#pragma once

#include <proto23/proto23.h>

#include <cstddef>
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>

struct Message3;
struct Message3Optional;

struct Message3 {
    enum class Enum : std::int32_t {
        FOO = 0,
        BAR = 1,
        BAZ = 2,
        EXTRA_3 = 30,
    };

    proto23::int32 optional_int32{};
    proto23::int64 optional_int64{};
    std::uint32_t optional_uint32{};
    std::uint64_t optional_uint64{};
    std::int32_t optional_sint32{};
    std::int64_t optional_sint64{};
    proto23::fixed32 optional_fixed32{};
    proto23::fixed64 optional_fixed64{};
    proto23::sfixed32 optional_sfixed32{};
    proto23::sfixed64 optional_sfixed64{};
    float optional_float{};
    double optional_double{};
    bool optional_bool{};
    std::string optional_string{};
    std::vector<std::byte> optional_bytes{};
    std::unique_ptr<Message3> optional_message;
    Message3::Enum optional_enum{};
    std::vector<proto23::int32> repeated_int32{};
    std::vector<proto23::int64> repeated_int64{};
    std::vector<std::uint32_t> repeated_uint32{};
    std::vector<std::uint64_t> repeated_uint64{};
    std::vector<std::int32_t> repeated_sint32{};
    std::vector<std::int64_t> repeated_sint64{};
    std::vector<proto23::fixed32> repeated_fixed32{};
    std::vector<proto23::fixed64> repeated_fixed64{};
    std::vector<proto23::sfixed32> repeated_sfixed32{};
    std::vector<proto23::sfixed64> repeated_sfixed64{};
    std::vector<float> repeated_float{};
    std::vector<double> repeated_double{};
    std::vector<bool> repeated_bool{};
    std::vector<std::string> repeated_string{};
    std::vector<std::vector<std::byte>> repeated_bytes{};
    std::vector<Message3> repeated_message;
    std::vector<Message3::Enum> repeated_enum{};
    std::variant<proto23::int32, proto23::int64, std::uint32_t, std::uint64_t, std::int32_t, std::int64_t, proto23::fixed32, proto23::fixed64, proto23::sfixed32, proto23::sfixed64, float, double, bool, std::string, std::vector<std::byte>, std::unique_ptr<Message3>, Message3::Enum> o;
    std::map<proto23::int32, proto23::int32> map_int32_int32{};
    std::map<proto23::int64, proto23::int64> map_int64_int64{};
    std::map<std::uint32_t, std::uint32_t> map_uint32_uint32{};
    std::map<std::uint64_t, std::uint64_t> map_uint64_uint64{};
    std::map<std::int32_t, std::int32_t> map_sint32_sint32{};
    std::map<std::int64_t, std::int64_t> map_sint64_sint64{};
    std::map<proto23::fixed32, proto23::fixed32> map_fixed32_fixed32{};
    std::map<proto23::fixed64, proto23::fixed64> map_fixed64_fixed64{};
    std::map<proto23::sfixed32, proto23::sfixed32> map_sfixed32_sfixed32{};
    std::map<proto23::sfixed64, proto23::sfixed64> map_sfixed64_sfixed64{};
    std::map<proto23::int32, float> map_int32_float{};
    std::map<proto23::int32, double> map_int32_double{};
    std::map<bool, bool> map_bool_bool{};
    std::map<std::string, std::string> map_string_string{};
    std::map<std::string, std::vector<std::byte>> map_string_bytes{};
    std::map<std::string, Message3> map_string_message{};
    std::map<proto23::int32, std::vector<std::byte>> map_int32_bytes{};
    std::map<proto23::int32, Message3::Enum> map_int32_enum{};
    std::map<proto23::int32, Message3> map_int32_message{};

    using Model = proto23::Fields<
        proto23::Field<&Message3::optional_int32, 1>,
        proto23::Field<&Message3::optional_int64, 2>,
        proto23::Field<&Message3::optional_uint32, 3>,
        proto23::Field<&Message3::optional_uint64, 4>,
        proto23::Field<&Message3::optional_sint32, 5>,
        proto23::Field<&Message3::optional_sint64, 6>,
        proto23::Field<&Message3::optional_fixed32, 7>,
        proto23::Field<&Message3::optional_fixed64, 8>,
        proto23::Field<&Message3::optional_sfixed32, 9>,
        proto23::Field<&Message3::optional_sfixed64, 10>,
        proto23::Field<&Message3::optional_float, 11>,
        proto23::Field<&Message3::optional_double, 12>,
        proto23::Field<&Message3::optional_bool, 13>,
        proto23::Field<&Message3::optional_string, 14>,
        proto23::Field<&Message3::optional_bytes, 15>,
        proto23::Field<&Message3::optional_message, 18>,
        proto23::Field<&Message3::optional_enum, 19>,
        proto23::Field<&Message3::repeated_int32, 31>,
        proto23::Field<&Message3::repeated_int64, 32>,
        proto23::Field<&Message3::repeated_uint32, 33>,
        proto23::Field<&Message3::repeated_uint64, 34>,
        proto23::Field<&Message3::repeated_sint32, 35>,
        proto23::Field<&Message3::repeated_sint64, 36>,
        proto23::Field<&Message3::repeated_fixed32, 37>,
        proto23::Field<&Message3::repeated_fixed64, 38>,
        proto23::Field<&Message3::repeated_sfixed32, 39>,
        proto23::Field<&Message3::repeated_sfixed64, 40>,
        proto23::Field<&Message3::repeated_float, 41>,
        proto23::Field<&Message3::repeated_double, 42>,
        proto23::Field<&Message3::repeated_bool, 43>,
        proto23::Field<&Message3::repeated_string, 44>,
        proto23::Field<&Message3::repeated_bytes, 45>,
        proto23::Field<&Message3::repeated_message, 48>,
        proto23::Field<&Message3::repeated_enum, 49>,
        proto23::OneOf<&Message3::o, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 68, 69>,
        proto23::Field<&Message3::map_int32_int32, 70>,
        proto23::Field<&Message3::map_int64_int64, 71>,
        proto23::Field<&Message3::map_uint32_uint32, 72>,
        proto23::Field<&Message3::map_uint64_uint64, 73>,
        proto23::Field<&Message3::map_sint32_sint32, 74>,
        proto23::Field<&Message3::map_sint64_sint64, 75>,
        proto23::Field<&Message3::map_fixed32_fixed32, 76>,
        proto23::Field<&Message3::map_fixed64_fixed64, 77>,
        proto23::Field<&Message3::map_sfixed32_sfixed32, 78>,
        proto23::Field<&Message3::map_sfixed64_sfixed64, 79>,
        proto23::Field<&Message3::map_int32_float, 80>,
        proto23::Field<&Message3::map_int32_double, 81>,
        proto23::Field<&Message3::map_bool_bool, 82>,
        proto23::Field<&Message3::map_string_string, 83>,
        proto23::Field<&Message3::map_string_bytes, 84>,
        proto23::Field<&Message3::map_string_message, 85>,
        proto23::Field<&Message3::map_int32_bytes, 86>,
        proto23::Field<&Message3::map_int32_enum, 87>,
        proto23::Field<&Message3::map_int32_message, 88>>;
};

struct Message3Optional {
    enum class Enum : std::int32_t {
        FOO = 0,
        BAR = 1,
        BAZ = 2,
        EXTRA_3 = 30,
    };

    std::optional<proto23::int32> optional_int32{};
    std::optional<proto23::int64> optional_int64{};
    std::optional<std::uint32_t> optional_uint32{};
    std::optional<std::uint64_t> optional_uint64{};
    std::optional<std::int32_t> optional_sint32{};
    std::optional<std::int64_t> optional_sint64{};
    std::optional<proto23::fixed32> optional_fixed32{};
    std::optional<proto23::fixed64> optional_fixed64{};
    std::optional<proto23::sfixed32> optional_sfixed32{};
    std::optional<proto23::sfixed64> optional_sfixed64{};
    std::optional<float> optional_float{};
    std::optional<double> optional_double{};
    std::optional<bool> optional_bool{};
    std::optional<std::string> optional_string{};
    std::optional<std::vector<std::byte>> optional_bytes{};
    std::unique_ptr<Message3> optional_message;
    std::optional<Message3Optional::Enum> optional_enum{};

    using Model = proto23::Fields<
        proto23::Field<&Message3Optional::optional_int32, 1>,
        proto23::Field<&Message3Optional::optional_int64, 2>,
        proto23::Field<&Message3Optional::optional_uint32, 3>,
        proto23::Field<&Message3Optional::optional_uint64, 4>,
        proto23::Field<&Message3Optional::optional_sint32, 5>,
        proto23::Field<&Message3Optional::optional_sint64, 6>,
        proto23::Field<&Message3Optional::optional_fixed32, 7>,
        proto23::Field<&Message3Optional::optional_fixed64, 8>,
        proto23::Field<&Message3Optional::optional_sfixed32, 9>,
        proto23::Field<&Message3Optional::optional_sfixed64, 10>,
        proto23::Field<&Message3Optional::optional_float, 11>,
        proto23::Field<&Message3Optional::optional_double, 12>,
        proto23::Field<&Message3Optional::optional_bool, 13>,
        proto23::Field<&Message3Optional::optional_string, 14>,
        proto23::Field<&Message3Optional::optional_bytes, 15>,
        proto23::Field<&Message3Optional::optional_message, 18>,
        proto23::Field<&Message3Optional::optional_enum, 19>>;
};

