// Generated by protoc-gen-proto23 -- DO NOT EDIT
// Source: unittest_well_known_types.proto

#pragma once

#include <proto23/proto23.h>

#include <cstddef>
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>

#include "google/protobuf/any.proto23.h"
#include "google/protobuf/api.proto23.h"
#include "google/protobuf/duration.proto23.h"
#include "google/protobuf/empty.proto23.h"
#include "google/protobuf/field_mask.proto23.h"
#include "google/protobuf/source_context.proto23.h"
#include "google/protobuf/struct.proto23.h"
#include "google/protobuf/timestamp.proto23.h"
#include "google/protobuf/type.proto23.h"
#include "google/protobuf/wrappers.proto23.h"

struct TestWellKnownTypes;
struct RepeatedWellKnownTypes;
struct OneofWellKnownTypes;
struct MapWellKnownTypes;

struct TestWellKnownTypes {
    std::unique_ptr<google::protobuf::Any> any_field{};
    std::unique_ptr<google::protobuf::Api> api_field{};
    std::unique_ptr<google::protobuf::Duration> duration_field{};
    std::unique_ptr<google::protobuf::Empty> empty_field{};
    std::unique_ptr<google::protobuf::FieldMask> field_mask_field{};
    std::unique_ptr<google::protobuf::SourceContext> source_context_field{};
    std::unique_ptr<google::protobuf::Struct> struct_field{};
    std::unique_ptr<google::protobuf::Timestamp> timestamp_field{};
    std::unique_ptr<google::protobuf::Type> type_field{};
    std::unique_ptr<google::protobuf::DoubleValue> double_field{};
    std::unique_ptr<google::protobuf::FloatValue> float_field{};
    std::unique_ptr<google::protobuf::Int64Value> int64_field{};
    std::unique_ptr<google::protobuf::UInt64Value> uint64_field{};
    std::unique_ptr<google::protobuf::Int32Value> int32_field{};
    std::unique_ptr<google::protobuf::UInt32Value> uint32_field{};
    std::unique_ptr<google::protobuf::BoolValue> bool_field{};
    std::unique_ptr<google::protobuf::StringValue> string_field{};
    std::unique_ptr<google::protobuf::BytesValue> bytes_field{};
    std::unique_ptr<google::protobuf::Value> value_field{};

    using Model = proto23::Fields<
        proto23::Field<&TestWellKnownTypes::any_field, 1>,
        proto23::Field<&TestWellKnownTypes::api_field, 2>,
        proto23::Field<&TestWellKnownTypes::duration_field, 3>,
        proto23::Field<&TestWellKnownTypes::empty_field, 4>,
        proto23::Field<&TestWellKnownTypes::field_mask_field, 5>,
        proto23::Field<&TestWellKnownTypes::source_context_field, 6>,
        proto23::Field<&TestWellKnownTypes::struct_field, 7>,
        proto23::Field<&TestWellKnownTypes::timestamp_field, 8>,
        proto23::Field<&TestWellKnownTypes::type_field, 9>,
        proto23::Field<&TestWellKnownTypes::double_field, 10>,
        proto23::Field<&TestWellKnownTypes::float_field, 11>,
        proto23::Field<&TestWellKnownTypes::int64_field, 12>,
        proto23::Field<&TestWellKnownTypes::uint64_field, 13>,
        proto23::Field<&TestWellKnownTypes::int32_field, 14>,
        proto23::Field<&TestWellKnownTypes::uint32_field, 15>,
        proto23::Field<&TestWellKnownTypes::bool_field, 16>,
        proto23::Field<&TestWellKnownTypes::string_field, 17>,
        proto23::Field<&TestWellKnownTypes::bytes_field, 18>,
        proto23::Field<&TestWellKnownTypes::value_field, 19>>;
};

struct RepeatedWellKnownTypes {
    std::vector<google::protobuf::Any> any_field{};
    std::vector<google::protobuf::Api> api_field{};
    std::vector<google::protobuf::Duration> duration_field{};
    std::vector<google::protobuf::Empty> empty_field{};
    std::vector<google::protobuf::FieldMask> field_mask_field{};
    std::vector<google::protobuf::SourceContext> source_context_field{};
    std::vector<google::protobuf::Struct> struct_field{};
    std::vector<google::protobuf::Timestamp> timestamp_field{};
    std::vector<google::protobuf::Type> type_field{};
    std::vector<google::protobuf::DoubleValue> double_field{};
    std::vector<google::protobuf::FloatValue> float_field{};
    std::vector<google::protobuf::Int64Value> int64_field{};
    std::vector<google::protobuf::UInt64Value> uint64_field{};
    std::vector<google::protobuf::Int32Value> int32_field{};
    std::vector<google::protobuf::UInt32Value> uint32_field{};
    std::vector<google::protobuf::BoolValue> bool_field{};
    std::vector<google::protobuf::StringValue> string_field{};
    std::vector<google::protobuf::BytesValue> bytes_field{};

    using Model = proto23::Fields<
        proto23::Field<&RepeatedWellKnownTypes::any_field, 1>,
        proto23::Field<&RepeatedWellKnownTypes::api_field, 2>,
        proto23::Field<&RepeatedWellKnownTypes::duration_field, 3>,
        proto23::Field<&RepeatedWellKnownTypes::empty_field, 4>,
        proto23::Field<&RepeatedWellKnownTypes::field_mask_field, 5>,
        proto23::Field<&RepeatedWellKnownTypes::source_context_field, 6>,
        proto23::Field<&RepeatedWellKnownTypes::struct_field, 7>,
        proto23::Field<&RepeatedWellKnownTypes::timestamp_field, 8>,
        proto23::Field<&RepeatedWellKnownTypes::type_field, 9>,
        proto23::Field<&RepeatedWellKnownTypes::double_field, 10>,
        proto23::Field<&RepeatedWellKnownTypes::float_field, 11>,
        proto23::Field<&RepeatedWellKnownTypes::int64_field, 12>,
        proto23::Field<&RepeatedWellKnownTypes::uint64_field, 13>,
        proto23::Field<&RepeatedWellKnownTypes::int32_field, 14>,
        proto23::Field<&RepeatedWellKnownTypes::uint32_field, 15>,
        proto23::Field<&RepeatedWellKnownTypes::bool_field, 16>,
        proto23::Field<&RepeatedWellKnownTypes::string_field, 17>,
        proto23::Field<&RepeatedWellKnownTypes::bytes_field, 18>>;
};

struct OneofWellKnownTypes {
    std::variant<google::protobuf::Any, google::protobuf::Api, google::protobuf::Duration, google::protobuf::Empty, google::protobuf::FieldMask, google::protobuf::SourceContext, google::protobuf::Struct, google::protobuf::Timestamp, google::protobuf::Type, google::protobuf::DoubleValue, google::protobuf::FloatValue, google::protobuf::Int64Value, google::protobuf::UInt64Value, google::protobuf::Int32Value, google::protobuf::UInt32Value, google::protobuf::BoolValue, google::protobuf::StringValue, google::protobuf::BytesValue> oneof_field{};

    using Model = proto23::Fields<
        proto23::OneOf<&OneofWellKnownTypes::oneof_field, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18>>;
};

struct MapWellKnownTypes {
    std::map<proto23::int32, google::protobuf::Any> any_field{};
    std::map<proto23::int32, google::protobuf::Api> api_field{};
    std::map<proto23::int32, google::protobuf::Duration> duration_field{};
    std::map<proto23::int32, google::protobuf::Empty> empty_field{};
    std::map<proto23::int32, google::protobuf::FieldMask> field_mask_field{};
    std::map<proto23::int32, google::protobuf::SourceContext> source_context_field{};
    std::map<proto23::int32, google::protobuf::Struct> struct_field{};
    std::map<proto23::int32, google::protobuf::Timestamp> timestamp_field{};
    std::map<proto23::int32, google::protobuf::Type> type_field{};
    std::map<proto23::int32, google::protobuf::DoubleValue> double_field{};
    std::map<proto23::int32, google::protobuf::FloatValue> float_field{};
    std::map<proto23::int32, google::protobuf::Int64Value> int64_field{};
    std::map<proto23::int32, google::protobuf::UInt64Value> uint64_field{};
    std::map<proto23::int32, google::protobuf::Int32Value> int32_field{};
    std::map<proto23::int32, google::protobuf::UInt32Value> uint32_field{};
    std::map<proto23::int32, google::protobuf::BoolValue> bool_field{};
    std::map<proto23::int32, google::protobuf::StringValue> string_field{};
    std::map<proto23::int32, google::protobuf::BytesValue> bytes_field{};

    using Model = proto23::Fields<
        proto23::Field<&MapWellKnownTypes::any_field, 1>,
        proto23::Field<&MapWellKnownTypes::api_field, 2>,
        proto23::Field<&MapWellKnownTypes::duration_field, 3>,
        proto23::Field<&MapWellKnownTypes::empty_field, 4>,
        proto23::Field<&MapWellKnownTypes::field_mask_field, 5>,
        proto23::Field<&MapWellKnownTypes::source_context_field, 6>,
        proto23::Field<&MapWellKnownTypes::struct_field, 7>,
        proto23::Field<&MapWellKnownTypes::timestamp_field, 8>,
        proto23::Field<&MapWellKnownTypes::type_field, 9>,
        proto23::Field<&MapWellKnownTypes::double_field, 10>,
        proto23::Field<&MapWellKnownTypes::float_field, 11>,
        proto23::Field<&MapWellKnownTypes::int64_field, 12>,
        proto23::Field<&MapWellKnownTypes::uint64_field, 13>,
        proto23::Field<&MapWellKnownTypes::int32_field, 14>,
        proto23::Field<&MapWellKnownTypes::uint32_field, 15>,
        proto23::Field<&MapWellKnownTypes::bool_field, 16>,
        proto23::Field<&MapWellKnownTypes::string_field, 17>,
        proto23::Field<&MapWellKnownTypes::bytes_field, 18>>;
};

