// Generated by protoc-gen-proto23 -- DO NOT EDIT
// Source: unittest_proto3.proto

#pragma once

#include <proto23/proto23.h>

#include <cstddef>
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>

#include "google/protobuf/unittest_import.proto23.h"

struct TestAllTypes;
struct TestPackedTypes;
struct TestUnpackedTypes;
struct NestedTestAllTypes;
struct ForeignMessage;
struct TestEmptyMessage;
struct TestMessageWithDummy;
struct TestOneof2;
struct TestHasbits;

enum class ForeignEnum : std::int32_t {
    FOREIGN_ZERO = 0,
    FOREIGN_FOO = 4,
    FOREIGN_BAR = 5,
    FOREIGN_BAZ = 6,
    FOREIGN_LARGE = 123456,
};

struct TestAllTypes {
    enum class NestedEnum : std::int32_t {
        ZERO = 0,
        FOO = 1,
        BAR = 2,
        BAZ = 3,
        NEG = -1,
    };

    struct NestedMessage {
        proto23::int32 bb{};

        using Model = proto23::Fields<
            proto23::Field<&NestedMessage::bb, 1>>;
    };

    proto23::int32 optional_int32{};
    proto23::int64 optional_int64{};
    std::uint32_t optional_uint32{};
    std::uint64_t optional_uint64{};
    std::int32_t optional_sint32{};
    std::int64_t optional_sint64{};
    proto23::fixed32 optional_fixed32{};
    proto23::fixed64 optional_fixed64{};
    proto23::sfixed32 optional_sfixed32{};
    proto23::sfixed64 optional_sfixed64{};
    float optional_float{};
    double optional_double{};
    bool optional_bool{};
    std::string optional_string{};
    std::vector<std::byte> optional_bytes{};
    std::optional<TestAllTypes::NestedMessage> optional_nested_message{};
    std::unique_ptr<ForeignMessage> optional_foreign_message;
    std::unique_ptr<proto2_unittest_import::ImportMessage> optional_import_message{};
    TestAllTypes::NestedEnum optional_nested_enum{};
    ForeignEnum optional_foreign_enum{};
    std::string optional_string_piece{};
    std::string optional_cord{};
    std::unique_ptr<proto2_unittest_import::PublicImportMessage> optional_public_import_message{};
    TestAllTypes::NestedMessage optional_lazy_message{};
    TestAllTypes::NestedMessage optional_unverified_lazy_message{};
    std::unique_ptr<proto2_unittest_import::ImportMessage> optional_lazy_import_message{};
    std::vector<proto23::int32> repeated_int32{};
    std::vector<proto23::int64> repeated_int64{};
    std::vector<std::uint32_t> repeated_uint32{};
    std::vector<std::uint64_t> repeated_uint64{};
    std::vector<std::int32_t> repeated_sint32{};
    std::vector<std::int64_t> repeated_sint64{};
    std::vector<proto23::fixed32> repeated_fixed32{};
    std::vector<proto23::fixed64> repeated_fixed64{};
    std::vector<proto23::sfixed32> repeated_sfixed32{};
    std::vector<proto23::sfixed64> repeated_sfixed64{};
    std::vector<float> repeated_float{};
    std::vector<double> repeated_double{};
    std::vector<bool> repeated_bool{};
    std::vector<std::string> repeated_string{};
    std::vector<std::vector<std::byte>> repeated_bytes{};
    std::vector<TestAllTypes::NestedMessage> repeated_nested_message{};
    std::vector<ForeignMessage> repeated_foreign_message;
    std::vector<proto2_unittest_import::ImportMessage> repeated_import_message{};
    std::vector<TestAllTypes::NestedEnum> repeated_nested_enum{};
    std::vector<ForeignEnum> repeated_foreign_enum{};
    std::vector<std::string> repeated_string_piece{};
    std::vector<std::string> repeated_cord{};
    std::vector<TestAllTypes::NestedMessage> repeated_lazy_message{};
    std::variant<std::uint32_t, TestAllTypes::NestedMessage, std::string, std::vector<std::byte>> oneof_field{};

    using Model = proto23::Fields<
        proto23::Field<&TestAllTypes::optional_int32, 1>,
        proto23::Field<&TestAllTypes::optional_int64, 2>,
        proto23::Field<&TestAllTypes::optional_uint32, 3>,
        proto23::Field<&TestAllTypes::optional_uint64, 4>,
        proto23::Field<&TestAllTypes::optional_sint32, 5>,
        proto23::Field<&TestAllTypes::optional_sint64, 6>,
        proto23::Field<&TestAllTypes::optional_fixed32, 7>,
        proto23::Field<&TestAllTypes::optional_fixed64, 8>,
        proto23::Field<&TestAllTypes::optional_sfixed32, 9>,
        proto23::Field<&TestAllTypes::optional_sfixed64, 10>,
        proto23::Field<&TestAllTypes::optional_float, 11>,
        proto23::Field<&TestAllTypes::optional_double, 12>,
        proto23::Field<&TestAllTypes::optional_bool, 13>,
        proto23::Field<&TestAllTypes::optional_string, 14>,
        proto23::Field<&TestAllTypes::optional_bytes, 15>,
        proto23::Field<&TestAllTypes::optional_nested_message, 18>,
        proto23::Field<&TestAllTypes::optional_foreign_message, 19>,
        proto23::Field<&TestAllTypes::optional_import_message, 20>,
        proto23::Field<&TestAllTypes::optional_nested_enum, 21>,
        proto23::Field<&TestAllTypes::optional_foreign_enum, 22>,
        proto23::Field<&TestAllTypes::optional_string_piece, 24>,
        proto23::Field<&TestAllTypes::optional_cord, 25>,
        proto23::Field<&TestAllTypes::optional_public_import_message, 26>,
        proto23::Field<&TestAllTypes::optional_lazy_message, 27>,
        proto23::Field<&TestAllTypes::optional_unverified_lazy_message, 28>,
        proto23::Field<&TestAllTypes::optional_lazy_import_message, 115>,
        proto23::Field<&TestAllTypes::repeated_int32, 31>,
        proto23::Field<&TestAllTypes::repeated_int64, 32>,
        proto23::Field<&TestAllTypes::repeated_uint32, 33>,
        proto23::Field<&TestAllTypes::repeated_uint64, 34>,
        proto23::Field<&TestAllTypes::repeated_sint32, 35>,
        proto23::Field<&TestAllTypes::repeated_sint64, 36>,
        proto23::Field<&TestAllTypes::repeated_fixed32, 37>,
        proto23::Field<&TestAllTypes::repeated_fixed64, 38>,
        proto23::Field<&TestAllTypes::repeated_sfixed32, 39>,
        proto23::Field<&TestAllTypes::repeated_sfixed64, 40>,
        proto23::Field<&TestAllTypes::repeated_float, 41>,
        proto23::Field<&TestAllTypes::repeated_double, 42>,
        proto23::Field<&TestAllTypes::repeated_bool, 43>,
        proto23::Field<&TestAllTypes::repeated_string, 44>,
        proto23::Field<&TestAllTypes::repeated_bytes, 45>,
        proto23::Field<&TestAllTypes::repeated_nested_message, 48>,
        proto23::Field<&TestAllTypes::repeated_foreign_message, 49>,
        proto23::Field<&TestAllTypes::repeated_import_message, 50>,
        proto23::Field<&TestAllTypes::repeated_nested_enum, 51>,
        proto23::Field<&TestAllTypes::repeated_foreign_enum, 52>,
        proto23::Field<&TestAllTypes::repeated_string_piece, 54, proto23::packed_t::no>,
        proto23::Field<&TestAllTypes::repeated_cord, 55, proto23::packed_t::no>,
        proto23::Field<&TestAllTypes::repeated_lazy_message, 57>,
        proto23::OneOf<&TestAllTypes::oneof_field, 111, 112, 113, 114>>;
};

struct TestPackedTypes {
    std::vector<proto23::int32> packed_int32{};
    std::vector<proto23::int64> packed_int64{};
    std::vector<std::uint32_t> packed_uint32{};
    std::vector<std::uint64_t> packed_uint64{};
    std::vector<std::int32_t> packed_sint32{};
    std::vector<std::int64_t> packed_sint64{};
    std::vector<proto23::fixed32> packed_fixed32{};
    std::vector<proto23::fixed64> packed_fixed64{};
    std::vector<proto23::sfixed32> packed_sfixed32{};
    std::vector<proto23::sfixed64> packed_sfixed64{};
    std::vector<float> packed_float{};
    std::vector<double> packed_double{};
    std::vector<bool> packed_bool{};
    std::vector<ForeignEnum> packed_enum{};

    using Model = proto23::Fields<
        proto23::Field<&TestPackedTypes::packed_int32, 90>,
        proto23::Field<&TestPackedTypes::packed_int64, 91>,
        proto23::Field<&TestPackedTypes::packed_uint32, 92>,
        proto23::Field<&TestPackedTypes::packed_uint64, 93>,
        proto23::Field<&TestPackedTypes::packed_sint32, 94>,
        proto23::Field<&TestPackedTypes::packed_sint64, 95>,
        proto23::Field<&TestPackedTypes::packed_fixed32, 96>,
        proto23::Field<&TestPackedTypes::packed_fixed64, 97>,
        proto23::Field<&TestPackedTypes::packed_sfixed32, 98>,
        proto23::Field<&TestPackedTypes::packed_sfixed64, 99>,
        proto23::Field<&TestPackedTypes::packed_float, 100>,
        proto23::Field<&TestPackedTypes::packed_double, 101>,
        proto23::Field<&TestPackedTypes::packed_bool, 102>,
        proto23::Field<&TestPackedTypes::packed_enum, 103>>;
};

struct TestUnpackedTypes {
    std::vector<proto23::int32> repeated_int32{};
    std::vector<proto23::int64> repeated_int64{};
    std::vector<std::uint32_t> repeated_uint32{};
    std::vector<std::uint64_t> repeated_uint64{};
    std::vector<std::int32_t> repeated_sint32{};
    std::vector<std::int64_t> repeated_sint64{};
    std::vector<proto23::fixed32> repeated_fixed32{};
    std::vector<proto23::fixed64> repeated_fixed64{};
    std::vector<proto23::sfixed32> repeated_sfixed32{};
    std::vector<proto23::sfixed64> repeated_sfixed64{};
    std::vector<float> repeated_float{};
    std::vector<double> repeated_double{};
    std::vector<bool> repeated_bool{};
    std::vector<TestAllTypes::NestedEnum> repeated_nested_enum{};

    using Model = proto23::Fields<
        proto23::Field<&TestUnpackedTypes::repeated_int32, 1, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_int64, 2, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_uint32, 3, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_uint64, 4, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_sint32, 5, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_sint64, 6, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_fixed32, 7, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_fixed64, 8, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_sfixed32, 9, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_sfixed64, 10, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_float, 11, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_double, 12, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_bool, 13, proto23::packed_t::no>,
        proto23::Field<&TestUnpackedTypes::repeated_nested_enum, 14, proto23::packed_t::no>>;
};

struct NestedTestAllTypes {
    std::unique_ptr<NestedTestAllTypes> child;
    std::unique_ptr<TestAllTypes> payload;

    using Model = proto23::Fields<
        proto23::Field<&NestedTestAllTypes::child, 1>,
        proto23::Field<&NestedTestAllTypes::payload, 2>>;
};

struct ForeignMessage {
    proto23::int32 c{};

    using Model = proto23::Fields<
        proto23::Field<&ForeignMessage::c, 1>>;
};

struct TestEmptyMessage {
    // This message has no fields
};

struct TestMessageWithDummy {
    bool dummy{};

    using Model = proto23::Fields<
        proto23::Field<&TestMessageWithDummy::dummy, 536870911>>;
};

struct TestOneof2 {
    enum class NestedEnum : std::int32_t {
        UNKNOWN = 0,
        FOO = 1,
        BAR = 2,
        BAZ = 3,
    };

    std::variant<TestOneof2::NestedEnum> foo{};

    using Model = proto23::Fields<
        proto23::OneOf<&TestOneof2::foo, 6>>;
};

struct TestHasbits {
    bool b1{};
    bool b2{};
    bool b3{};
    bool b4{};
    bool b5{};
    bool b6{};
    bool b7{};
    bool b8{};
    bool b9{};
    bool b10{};
    bool b11{};
    bool b12{};
    bool b13{};
    bool b14{};
    bool b15{};
    bool b16{};
    bool b17{};
    bool b18{};
    bool b19{};
    bool b20{};
    bool b21{};
    bool b22{};
    bool b23{};
    bool b24{};
    bool b25{};
    bool b26{};
    bool b27{};
    bool b28{};
    bool b29{};
    bool b30{};
    bool b31{};
    bool b32{};
    bool b33{};
    bool b34{};
    bool b35{};
    bool b36{};
    bool b37{};
    bool b38{};
    bool b39{};
    bool b40{};
    bool b41{};
    bool b42{};
    bool b43{};
    bool b44{};
    bool b45{};
    bool b46{};
    bool b47{};
    bool b48{};
    bool b49{};
    bool b50{};
    bool b51{};
    bool b52{};
    bool b53{};
    bool b54{};
    bool b55{};
    bool b56{};
    bool b57{};
    bool b58{};
    bool b59{};
    bool b60{};
    bool b61{};
    bool b62{};
    bool b63{};
    bool b64{};
    bool b65{};
    bool b66{};
    bool b67{};
    bool b68{};
    bool b69{};
    std::unique_ptr<TestAllTypes> child;

    using Model = proto23::Fields<
        proto23::Field<&TestHasbits::b1, 1>,
        proto23::Field<&TestHasbits::b2, 2>,
        proto23::Field<&TestHasbits::b3, 3>,
        proto23::Field<&TestHasbits::b4, 4>,
        proto23::Field<&TestHasbits::b5, 5>,
        proto23::Field<&TestHasbits::b6, 6>,
        proto23::Field<&TestHasbits::b7, 7>,
        proto23::Field<&TestHasbits::b8, 8>,
        proto23::Field<&TestHasbits::b9, 9>,
        proto23::Field<&TestHasbits::b10, 10>,
        proto23::Field<&TestHasbits::b11, 11>,
        proto23::Field<&TestHasbits::b12, 12>,
        proto23::Field<&TestHasbits::b13, 13>,
        proto23::Field<&TestHasbits::b14, 14>,
        proto23::Field<&TestHasbits::b15, 15>,
        proto23::Field<&TestHasbits::b16, 16>,
        proto23::Field<&TestHasbits::b17, 17>,
        proto23::Field<&TestHasbits::b18, 18>,
        proto23::Field<&TestHasbits::b19, 19>,
        proto23::Field<&TestHasbits::b20, 20>,
        proto23::Field<&TestHasbits::b21, 21>,
        proto23::Field<&TestHasbits::b22, 22>,
        proto23::Field<&TestHasbits::b23, 23>,
        proto23::Field<&TestHasbits::b24, 24>,
        proto23::Field<&TestHasbits::b25, 25>,
        proto23::Field<&TestHasbits::b26, 26>,
        proto23::Field<&TestHasbits::b27, 27>,
        proto23::Field<&TestHasbits::b28, 28>,
        proto23::Field<&TestHasbits::b29, 29>,
        proto23::Field<&TestHasbits::b30, 30>,
        proto23::Field<&TestHasbits::b31, 31>,
        proto23::Field<&TestHasbits::b32, 32>,
        proto23::Field<&TestHasbits::b33, 33>,
        proto23::Field<&TestHasbits::b34, 34>,
        proto23::Field<&TestHasbits::b35, 35>,
        proto23::Field<&TestHasbits::b36, 36>,
        proto23::Field<&TestHasbits::b37, 37>,
        proto23::Field<&TestHasbits::b38, 38>,
        proto23::Field<&TestHasbits::b39, 39>,
        proto23::Field<&TestHasbits::b40, 40>,
        proto23::Field<&TestHasbits::b41, 41>,
        proto23::Field<&TestHasbits::b42, 42>,
        proto23::Field<&TestHasbits::b43, 43>,
        proto23::Field<&TestHasbits::b44, 44>,
        proto23::Field<&TestHasbits::b45, 45>,
        proto23::Field<&TestHasbits::b46, 46>,
        proto23::Field<&TestHasbits::b47, 47>,
        proto23::Field<&TestHasbits::b48, 48>,
        proto23::Field<&TestHasbits::b49, 49>,
        proto23::Field<&TestHasbits::b50, 50>,
        proto23::Field<&TestHasbits::b51, 51>,
        proto23::Field<&TestHasbits::b52, 52>,
        proto23::Field<&TestHasbits::b53, 53>,
        proto23::Field<&TestHasbits::b54, 54>,
        proto23::Field<&TestHasbits::b55, 55>,
        proto23::Field<&TestHasbits::b56, 56>,
        proto23::Field<&TestHasbits::b57, 57>,
        proto23::Field<&TestHasbits::b58, 58>,
        proto23::Field<&TestHasbits::b59, 59>,
        proto23::Field<&TestHasbits::b60, 60>,
        proto23::Field<&TestHasbits::b61, 61>,
        proto23::Field<&TestHasbits::b62, 62>,
        proto23::Field<&TestHasbits::b63, 63>,
        proto23::Field<&TestHasbits::b64, 64>,
        proto23::Field<&TestHasbits::b65, 65>,
        proto23::Field<&TestHasbits::b66, 66>,
        proto23::Field<&TestHasbits::b67, 67>,
        proto23::Field<&TestHasbits::b68, 68>,
        proto23::Field<&TestHasbits::b69, 69>,
        proto23::Field<&TestHasbits::child, 100>>;
};

